// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\AXIS_master_FIFO_rd_DIRTY\AXIS_master_FIFO_rd_DIRTY.v
// Created: 2026-04-29 10:01:06
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: AXIS_master_FIFO_rd_DIRTY
// Source Path: AXIS_master_FIFO_rd_DIRTY
// Hierarchy Level: 0
// Model version: 16.419
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AXIS_master_FIFO_rd_DIRTY
          (clk,
           reset,
           lane_up,
           channel_up,
           m_axi_tready,
           s_axi_tdata,
           s_axi_tvalid,
           s_axi_tlast,
           s_axi_tkeep,
           s_axi_tuser,
           m_axi_nfc_ack,
           s_axi_rx_snf,
           s_axi_rx_fc_nb,
           LinkPartner_XOFF,
           dbg_NFC_NB_in,
           D_FIFO_rd_aempty,
           D_FIFO_rd_data,
           D_WORD_rd_empty,
           D_WORD_rd_data,
           D_FIFO_rd_empty,
           N,
           m_axi_tdata,
           m_axi_tvalid,
           m_axi_tlast,
           m_axi_tkeep,
           m_axi_tuser,
           dbg_state_out,
           m_axi_nfc_req,
           m_axi_nfc_nb,
           dbg_NFC_rcvd_value,
           dbg_rxerr_out,
           D_FIFO_rd_en,
           D_WORD_rd_en);


  input   clk;
  input   reset;
  input   lane_up;
  input   channel_up;
  input   m_axi_tready;
  input   [31:0] s_axi_tdata;  // uint32
  input   s_axi_tvalid;
  input   s_axi_tlast;
  input   [3:0] s_axi_tkeep;  // ufix4
  input   s_axi_tuser;
  input   m_axi_nfc_ack;
  input   s_axi_rx_snf;
  input   [3:0] s_axi_rx_fc_nb;  // ufix4
  input   LinkPartner_XOFF;
  input   [3:0] dbg_NFC_NB_in;  // ufix4
  input   D_FIFO_rd_aempty;
  input   [31:0] D_FIFO_rd_data;  // uint32
  input   D_WORD_rd_empty;
  input   [15:0] D_WORD_rd_data;  // uint16
  input   D_FIFO_rd_empty;
  input   [7:0] N;  // uint8
  output  [31:0] m_axi_tdata;  // uint32
  output  m_axi_tvalid;
  output  m_axi_tlast;
  output  [3:0] m_axi_tkeep;  // ufix4
  output  m_axi_tuser;
  output  [1:0] dbg_state_out;  // ufix2
  output  m_axi_nfc_req;
  output  m_axi_nfc_nb;
  output  dbg_NFC_rcvd_value;
  output  dbg_rxerr_out;
  output  D_FIFO_rd_en;
  output  D_WORD_rd_en;


  reg [31:0] m_axis_tdata;  // uint32
  reg  m_axis_tvalid;
  reg  m_axis_tlast;
  reg [3:0] m_axis_tkeep;  // ufix4
  reg  m_axis_tuser;
  reg [1:0] state;  // ufix2
  reg  m_axi_nfc_req_1;
  reg [3:0] m_axi_nfc_nb_1;  // ufix4
  reg [3:0] NFC_rcvd_value;  // ufix4
  reg  rx_err;
  reg  D_FIFO_rd_en_1;
  reg  D_WORD_rd_en_1;
  reg [1:0] tx_state_reg;  // ufix2
  reg [1:0] rx_state_reg;  // ufix2
  reg [2:0] flow_ctrl_state;  // ufix3
  reg  axi_nfc_req_tmp;
  reg [3:0] axi_nfc_nb_reg;  // ufix4
  reg [3:0] NFC_rcvd_value_reg;  // ufix4
  reg [7:0] beat_cnt;  // ufix8
  reg  in_valid;
  reg [31:0] in_data;  // ufix32
  reg [31:0] skid_data;  // ufix32
  reg  skid_last;
  reg  skid_valid;
  reg [31:0] m_axis_tdata_reg;  // ufix32
  reg  m_axis_tvalid_reg;
  reg  m_axis_tlast_reg;
  reg [31:0] rx_previous_reg;  // ufix32
  reg  rx_err_r;
  reg [1:0] tx_state_reg_next;  // ufix2
  reg [1:0] rx_state_reg_next;  // ufix2
  reg [2:0] flow_ctrl_state_next;  // ufix3
  reg  axi_nfc_req_tmp_next;
  reg [3:0] axi_nfc_nb_reg_next;  // ufix4
  reg [3:0] NFC_rcvd_value_reg_next;  // ufix4
  reg [7:0] beat_cnt_next;  // ufix8
  reg  in_valid_next;
  reg [31:0] in_data_next;  // ufix32
  reg [31:0] skid_data_next;  // ufix32
  reg  skid_last_next;
  reg  skid_valid_next;
  reg [31:0] m_axis_tdata_reg_next;  // ufix32
  reg  m_axis_tvalid_reg_next;
  reg  m_axis_tlast_reg_next;
  reg [31:0] rx_previous_reg_next;  // ufix32
  reg  rx_err_r_next;
  wire Zero_out1;
  reg [7:0] N1;  // ufix8
  reg  out_valid;
  reg  out_last;
  reg [31:0] out_data;  // ufix32
  reg  input_hold;
  reg  fsm_fire;
  reg  t_0;
  reg  can_pop;
  reg  input_will_be_free;
  reg  D_FIFO_rd_en1;
  reg [1:0] tx_state_reg_temp;  // ufix2
  reg [1:0] rx_state_reg_temp;  // ufix2
  reg [2:0] flow_ctrl_state_temp;  // ufix3
  reg  in_valid_temp;


  always @(posedge clk or posedge reset)
    begin : some_logic_DIRTY_process
      if (reset == 1'b1) begin
        tx_state_reg <= 2'b00;
        rx_state_reg <= 2'b00;
        flow_ctrl_state <= 3'b000;
        axi_nfc_req_tmp <= 1'b0;
        axi_nfc_nb_reg <= 4'b0000;
        NFC_rcvd_value_reg <= 4'b0000;
        beat_cnt <= 8'b00000000;
        in_valid <= 1'b0;
        in_data <= 32'b00000000000000000000000000000000;
        skid_data <= 32'b00000000000000000000000000000000;
        skid_last <= 1'b0;
        skid_valid <= 1'b0;
        m_axis_tdata_reg <= 32'b00000000000000000000000000000000;
        m_axis_tvalid_reg <= 1'b0;
        m_axis_tlast_reg <= 1'b0;
        rx_previous_reg <= 32'b00000000000000000000000000000000;
        rx_err_r <= 1'b0;
      end
      else begin
        tx_state_reg <= tx_state_reg_next;
        rx_state_reg <= rx_state_reg_next;
        flow_ctrl_state <= flow_ctrl_state_next;
        axi_nfc_req_tmp <= axi_nfc_req_tmp_next;
        axi_nfc_nb_reg <= axi_nfc_nb_reg_next;
        NFC_rcvd_value_reg <= NFC_rcvd_value_reg_next;
        beat_cnt <= beat_cnt_next;
        in_valid <= in_valid_next;
        in_data <= in_data_next;
        skid_data <= skid_data_next;
        skid_last <= skid_last_next;
        skid_valid <= skid_valid_next;
        m_axis_tdata_reg <= m_axis_tdata_reg_next;
        m_axis_tvalid_reg <= m_axis_tvalid_reg_next;
        m_axis_tlast_reg <= m_axis_tlast_reg_next;
        rx_previous_reg <= rx_previous_reg_next;
        rx_err_r <= rx_err_r_next;
      end
    end

  always @(D_FIFO_rd_data, D_FIFO_rd_empty, D_WORD_rd_data, LinkPartner_XOFF, N,
       NFC_rcvd_value_reg, axi_nfc_nb_reg, axi_nfc_req_tmp, beat_cnt,
       channel_up, flow_ctrl_state, in_data, in_valid, lane_up, m_axi_nfc_ack,
       m_axi_tready, m_axis_tdata_reg, m_axis_tlast_reg, m_axis_tvalid_reg,
       rx_err_r, rx_previous_reg, rx_state_reg, s_axi_rx_fc_nb, s_axi_rx_snf,
       s_axi_tdata, s_axi_tvalid, skid_data, skid_last, skid_valid,
       tx_state_reg) begin
    tx_state_reg_temp = tx_state_reg;
    rx_state_reg_temp = rx_state_reg;
    flow_ctrl_state_temp = flow_ctrl_state;
    in_valid_temp = in_valid;
    axi_nfc_req_tmp_next = axi_nfc_req_tmp;
    axi_nfc_nb_reg_next = axi_nfc_nb_reg;
    NFC_rcvd_value_reg_next = NFC_rcvd_value_reg;
    beat_cnt_next = beat_cnt;
    in_data_next = in_data;
    skid_data_next = skid_data;
    skid_last_next = skid_last;
    rx_previous_reg_next = rx_previous_reg;
    // Idle_Cycles_Requested = bin2dec('0011');
    N1 = N;
    // persistent data_counter_reg;
    // if isempty(data_counter_reg)
    //     data_counter_reg = fi(0,0,ceil(log2(2000)),0,fm);
    // end
    // ================= INPUT SKID BUFFER =================
    // * принимает данные из FIFO
    // * держит их, пока AXIS не готов
    // * позволяет корректно переживать tready=0
    // ================= SKID STATE (для gating) =================
    // persistent m_valid;
    // if isempty(m_valid), m_valid = false; end
    // ================= OUTPUT SKID  =====================
    // ================= OUTPUT =================
    // ================= FIFO READ (PREFETCH) =================
    // downstream full?
    fsm_fire = in_valid && ( ! skid_valid);
    // input_will_be_free = (~in_valid) || (in_valid && ~skid_full);
    // % * ~in_valid               -> буфер пуст
    // % * in_valid && ~skid_full  -> FSM точно съест данные в этом такте
    // 
    // D_FIFO_rd_en = (~D_FIFO_rd_empty) && input_will_be_free;
    // %% ================= INPUT BUFFER UPDATE =================
    // if D_FIFO_rd_en
    //     in_data  = fi(D_FIFO_rd_data, AXIS_nt, fm);
    //     in_valid = true;
    // elseif fsm_fire
    //     in_valid = false;
    // end
    rx_err_r_next = 1'b0;
    t_0 = lane_up && channel_up;
    if ( ! t_0) begin
      flow_ctrl_state_temp = 3'b000;
      tx_state_reg_temp = 2'b00;
      rx_state_reg_temp = 2'b00;
    end
    if (s_axi_rx_snf) begin
      NFC_rcvd_value_reg_next = s_axi_rx_fc_nb;
    end
    case ( rx_state_reg_temp)
      2'b00 :
        begin
          if (s_axi_tvalid) begin
            rx_previous_reg_next = s_axi_tdata;
            rx_state_reg_temp = 2'b01;
          end
          else begin
            rx_state_reg_temp = 2'b00;
          end
        end
      default :
        begin
          if (s_axi_tvalid) begin
            if (s_axi_tdata != (rx_previous_reg + 32'b00000000000000000000000000000001)) begin
              rx_err_r_next = 1'b1;
            end
            rx_previous_reg_next = s_axi_tdata;
          end
        end
    endcase
    case ( flow_ctrl_state_temp)
      3'b000 :
        begin
          if (lane_up && channel_up) begin
            flow_ctrl_state_temp = 3'b001;
          end
          else begin
            flow_ctrl_state_temp = 3'b000;
          end
        end
      3'b001 :
        begin
          if (LinkPartner_XOFF) begin
            // DISABLE Link Partner
            axi_nfc_req_tmp_next = 1'b1;
            // axi_nfc_nb_reg = fi(dbg_NFC_NB_in,0,axi_nfc_nb_reg.WordLength,0,fm);
            axi_nfc_nb_reg_next = 4'b1111;
            flow_ctrl_state_temp = 3'b010;
            // else
            //     flow_ctrl_state(1) = flow_ctrl_state(1);
          end
        end
      3'b010 :
        begin
          if (m_axi_nfc_ack) begin
            axi_nfc_req_tmp_next = 1'b0;
            flow_ctrl_state_temp = 3'b011;
          end
        end
      3'b011 :
        begin
          if ( ! LinkPartner_XOFF) begin
            // ENABLE Link Partner
            axi_nfc_req_tmp_next = 1'b1;
            // axi_nfc_nb_reg = fi(dbg_NFC_NB_in,0,axi_nfc_nb_reg.WordLength,0,fm);
            axi_nfc_nb_reg_next = 4'b0000;
            flow_ctrl_state_temp = 3'b100;
            // else
            //     flow_ctrl_state(1) = flow_ctrl_state(1);
          end
        end
      default :
        begin
          if (m_axi_nfc_ack) begin
            axi_nfc_req_tmp_next = 1'b0;
            flow_ctrl_state_temp = 3'b000;
          end
        end
    endcase
    // ================= FSM =================
    // FIFO → INPUT BUFFER → FSM → OUTPUT SKID → AXIS
    out_valid = 1'b0;
    out_last = 1'b0;
    out_data = 32'b00000000000000000000000000000000;
    input_hold = 1'b0;
    // fsm_fire = in_valid && ~skid_full;
    case ( tx_state_reg_temp)
      2'b00 :
        begin
          if (lane_up && channel_up) begin
            tx_state_reg_temp = 2'b01;
          end
          else begin
            tx_state_reg_temp = 2'b00;
          end
        end
      2'b01 :
        begin
          // if in_valid && ~skid_full
          if (fsm_fire) begin
            out_data = in_data;
            out_valid = 1'b1;
            // consume ТОЛЬКО здесь
            in_valid_temp = 1'b0;
            if (beat_cnt == (N1 - 8'b00000001)) begin
              tx_state_reg_temp = 2'b10;
              beat_cnt_next = 8'b00000000;
            end
            else begin
              beat_cnt_next = beat_cnt + 8'b00000001;
            end
          end
        end
      default :
        begin
          // send last (D_WORD_rd_data)
          // if (axis_ready_int)
          if ( ! skid_valid) begin
            out_data = {16'b0, D_WORD_rd_data};
            out_valid = 1'b1;
            out_last = 1'b1;
            tx_state_reg_temp = 2'b01;
          end
          input_hold = 1'b1;
        end
    endcase
    // ================= OUTPUT SKID =================
    // вход от FSM
    // ================= NEXT STATE LOGIC =================
    m_axis_tvalid_reg_next = m_axis_tvalid_reg;
    m_axis_tdata_reg_next = m_axis_tdata_reg;
    m_axis_tlast_reg_next = m_axis_tlast_reg;
    skid_valid_next = skid_valid;
    // ================= POP =================
    can_pop = m_axis_tvalid_reg && m_axi_tready;
    if (can_pop) begin
      if (skid_valid) begin
        m_axis_tdata_reg_next = skid_data;
        m_axis_tlast_reg_next = skid_last;
        m_axis_tvalid_reg_next = 1'b1;
        skid_valid_next = 1'b0;
      end
      else begin
        m_axis_tdata_reg_next = out_data;
        m_axis_tlast_reg_next = out_last;
        m_axis_tvalid_reg_next = out_valid;
      end
    end
    else if ( ! m_axis_tvalid_reg) begin
      // ===== BOOTSTRAP (SAFE) =====
      if (skid_valid) begin
        m_axis_tdata_reg_next = skid_data;
        m_axis_tlast_reg_next = skid_last;
        m_axis_tvalid_reg_next = 1'b1;
        skid_valid_next = 1'b0;
      end
      else if (out_valid) begin
        m_axis_tdata_reg_next = out_data;
        m_axis_tlast_reg_next = out_last;
        m_axis_tvalid_reg_next = 1'b1;
      end
    end
    // ================= PUSH =================
    if (out_valid) begin
      // ONLY BACKPRESSURE PATH
      if (m_axis_tvalid_reg && ( ! can_pop)) begin
        // output занят → backlog в skid
        skid_data_next = out_data;
        skid_last_next = out_last;
        skid_valid_next = 1'b1;
      end
      else if ((m_axis_tvalid_reg && can_pop) && skid_valid) begin
        // pop+push case → skid extension
        skid_data_next = out_data;
        skid_last_next = out_last;
        skid_valid_next = 1'b1;
        // elseif ~m_valid
        //     % ❌ ВАЖНО: убрали direct m write
        //     % ничего не делаем тут
        //     % (m заполняется ТОЛЬКО POP)
      end
    end
    input_will_be_free = ( ! in_valid_temp) || (in_valid_temp && ( ! skid_valid));
    // input_will_be_free = (~in_valid) || (in_valid && ~skid_valid);
    // * ~in_valid               -> буфер пуст
    // * in_valid && ~skid_full  -> FSM точно съест данные в этом такте
    // D_FIFO_rd_en = (~D_FIFO_rd_empty) && input_will_be_free;
    D_FIFO_rd_en1 = (( ! D_FIFO_rd_empty) && ( ! input_hold)) && input_will_be_free;
    // ================= INPUT BUFFER UPDATE =================
    if (D_FIFO_rd_en1) begin
      in_data_next = D_FIFO_rd_data;
      in_valid_temp = 1'b1;
    end
    m_axis_tdata = m_axis_tdata_reg;
    m_axis_tvalid = m_axis_tvalid_reg;
    m_axis_tlast = m_axis_tlast_reg;
    m_axis_tkeep = 4'b0000;
    m_axis_tuser = 1'b0;
    state = tx_state_reg;
    m_axi_nfc_req_1 = axi_nfc_req_tmp;
    m_axi_nfc_nb_1 = axi_nfc_nb_reg;
    NFC_rcvd_value = NFC_rcvd_value_reg;
    rx_err = rx_err_r;
    D_FIFO_rd_en_1 = D_FIFO_rd_en1;
    D_WORD_rd_en_1 = 1'b0;
    tx_state_reg_next = tx_state_reg_temp;
    rx_state_reg_next = rx_state_reg_temp;
    flow_ctrl_state_next = flow_ctrl_state_temp;
    in_valid_next = in_valid_temp;
  end



  assign m_axi_tdata = m_axis_tdata;

  assign m_axi_tvalid = m_axis_tvalid;

  assign m_axi_tlast = m_axis_tlast;

  assign m_axi_tkeep = m_axis_tkeep;

  assign m_axi_tuser = m_axis_tuser;

  assign dbg_state_out = state;

  assign Zero_out1 = 1'b0;



  assign m_axi_nfc_req = Zero_out1;

  assign m_axi_nfc_nb = Zero_out1;

  assign dbg_NFC_rcvd_value = Zero_out1;

  assign dbg_rxerr_out = Zero_out1;

  assign D_FIFO_rd_en = D_FIFO_rd_en_1;

  assign D_WORD_rd_en = D_WORD_rd_en_1;

endmodule  // AXIS_master_FIFO_rd_DIRTY

