// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\AXIS_master_FIFO_rd_2_WORD_FIFO\AXIS_master_FIFO_rd_2_WORD_FIFO.v
// Created: 2026-04-29 10:01:24
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: AXIS_master_FIFO_rd_2_WORD_FIFO
// Source Path: AXIS_master_FIFO_rd_2_WORD_FIFO
// Hierarchy Level: 0
// Model version: 16.417
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AXIS_master_FIFO_rd_2_WORD_FIFO
          (clk,
           reset,
           lane_up,
           channel_up,
           m_axi_tready,
           s_axi_tdata,
           s_axi_tvalid,
           s_axi_tlast,
           s_axi_tkeep,
           s_axi_tuser,
           m_axi_nfc_ack,
           s_axi_rx_snf,
           s_axi_rx_fc_nb,
           LinkPartner_XOFF,
           dbg_NFC_NB_in,
           D_FIFO_rd_aempty,
           D_FIFO_rd_data,
           D_WORD_rd_empty,
           D_WORD_rd_data,
           D_FIFO_rd_empty,
           N,
           m_axi_tdata,
           m_axi_tvalid,
           m_axi_tlast,
           m_axi_tkeep,
           m_axi_tuser,
           dbg_state_out,
           m_axi_nfc_req,
           m_axi_nfc_nb,
           dbg_NFC_rcvd_value,
           dbg_rxerr_out,
           D_FIFO_rd_en,
           D_WORD_rd_en);


  input   clk;
  input   reset;
  input   lane_up;
  input   channel_up;
  input   m_axi_tready;
  input   [31:0] s_axi_tdata;  // uint32
  input   s_axi_tvalid;
  input   s_axi_tlast;
  input   [3:0] s_axi_tkeep;  // ufix4
  input   s_axi_tuser;
  input   m_axi_nfc_ack;
  input   s_axi_rx_snf;
  input   [3:0] s_axi_rx_fc_nb;  // ufix4
  input   LinkPartner_XOFF;
  input   [3:0] dbg_NFC_NB_in;  // ufix4
  input   D_FIFO_rd_aempty;
  input   [31:0] D_FIFO_rd_data;  // uint32
  input   D_WORD_rd_empty;
  input   [15:0] D_WORD_rd_data;  // uint16
  input   D_FIFO_rd_empty;
  input   [7:0] N;  // uint8
  output  [31:0] m_axi_tdata;  // uint32
  output  m_axi_tvalid;
  output  m_axi_tlast;
  output  [3:0] m_axi_tkeep;  // ufix4
  output  m_axi_tuser;
  output  [1:0] dbg_state_out;  // ufix2
  output  m_axi_nfc_req;
  output  m_axi_nfc_nb;
  output  dbg_NFC_rcvd_value;
  output  dbg_rxerr_out;
  output  D_FIFO_rd_en;
  output  D_WORD_rd_en;


  reg [31:0] m_axis_tdata;  // uint32
  reg  m_axis_tvalid_1;
  reg  m_axis_tlast;
  reg [3:0] m_axis_tkeep;  // ufix4
  reg  m_axis_tuser;
  reg [1:0] state;  // ufix2
  reg  m_axi_nfc_req_1;
  reg [3:0] m_axi_nfc_nb_1;  // ufix4
  reg [3:0] NFC_rcvd_value;  // ufix4
  reg  rx_err;
  reg  D_FIFO_rd_en_1;
  reg  D_WORD_rd_en_1;
  reg [1:0] tx_state_reg;  // ufix2
  reg [7:0] beat_cnt;  // ufix8
  reg  in_valid;
  reg [31:0] in_data;  // ufix32
  reg [31:0] out_data0;  // ufix32
  reg [31:0] out_data1;  // ufix32
  reg  out_last0;
  reg  out_last1;
  reg [1:0] out_cnt;  // ufix2
  reg  rx_err_r;
  reg [1:0] tx_state_reg_next;  // ufix2
  reg [7:0] beat_cnt_next;  // ufix8
  reg  in_valid_next;
  reg [31:0] in_data_next;  // ufix32
  reg [31:0] out_data0_next;  // ufix32
  reg [31:0] out_data1_next;  // ufix32
  reg  out_last0_next;
  reg  out_last1_next;
  reg [1:0] out_cnt_next;  // ufix2
  reg  rx_err_r_next;
  wire Zero_out1;
  reg  m_axis_tvalid;
  reg [7:0] N1;  // ufix8
  reg  out_ready;
  reg  in_consumed;
  reg  out_valid;
  reg  out_last;
  reg [31:0] out_data;  // ufix32
  reg  axis_fire;
  reg  t_0;
  reg  D_FIFO_rd_en1;
  reg [1:0] tx_state_reg_temp;  // ufix2


  always @(posedge clk or posedge reset)
    begin : some_logic_2_WORD_FIFO_process
      if (reset == 1'b1) begin
        tx_state_reg <= 2'b00;
        beat_cnt <= 8'b00000000;
        in_valid <= 1'b0;
        in_data <= 32'b00000000000000000000000000000000;
        out_cnt <= 2'b00;
        out_data0 <= 32'b00000000000000000000000000000000;
        out_data1 <= 32'b00000000000000000000000000000000;
        out_last0 <= 1'b0;
        out_last1 <= 1'b0;
        rx_err_r <= 1'b0;
      end
      else begin
        tx_state_reg <= tx_state_reg_next;
        beat_cnt <= beat_cnt_next;
        in_valid <= in_valid_next;
        in_data <= in_data_next;
        out_data0 <= out_data0_next;
        out_data1 <= out_data1_next;
        out_last0 <= out_last0_next;
        out_last1 <= out_last1_next;
        out_cnt <= out_cnt_next;
        rx_err_r <= rx_err_r_next;
      end
    end

  always @(D_FIFO_rd_data, D_FIFO_rd_empty, D_WORD_rd_data, N, beat_cnt, channel_up,
       in_data, in_valid, lane_up, m_axi_tready, out_cnt, out_data0, out_data1,
       out_last0, out_last1, rx_err_r, tx_state_reg) begin
    tx_state_reg_temp = tx_state_reg;
    beat_cnt_next = beat_cnt;
    in_valid_next = in_valid;
    in_data_next = in_data;
    out_data0_next = out_data0;
    out_data1_next = out_data1;
    out_last0_next = out_last0;
    out_last1_next = out_last1;
    out_cnt_next = out_cnt;
    // Idle_Cycles_Requested = bin2dec('0011');
    N1 = N;
    // persistent data_counter_reg;
    // if isempty(data_counter_reg)
    //     data_counter_reg = fi(0,0,ceil(log2(2000)),0,fm);
    // end
    // ================= INPUT SKID BUFFER =================
    // * принимает данные из FIFO
    // * держит их, пока AXIS не готов
    // * позволяет корректно переживать tready=0
    // ================= 2-WORD OUTPUT FIFO =================
    // ================= OUTPUT =================
    m_axis_tvalid = out_cnt > 2'b00;
    axis_fire = m_axis_tvalid && m_axi_tready;
    rx_err_r_next = 1'b0;
    // ================= OUTPUT FIFO CONTROL =================
    // % push/pop signals
    // push = false;
    // push_data = fi(0, AXIS_nt, fm);
    // push_last = false;
    out_ready = out_cnt < 2'b10;
    // %% ================= FIFO READ =================
    // 
    // % Читаем FIFO, если он не пуст и либо входной буфер пуст,
    // % либо буфер полон, НО FSM сможет забрать из него слово (in_valid && out_ready)
    // % D_FIFO_rd_en = (~D_FIFO_rd_empty) && ( ~in_valid || (in_valid && out_ready) );
    // 
    // consume_input = tx_state_reg==1 && in_valid && out_ready;
    // D_FIFO_rd_en = (~D_FIFO_rd_empty) && ( ~in_valid || consume_input );
    // =========================================================
    // FSM STAGE
    // =========================================================
    //               in_consumed (от FSM!)
    //                       ↓
    // FIFO → [Input Buffer] ← [FSM] → [Output FIFO 2w] → AXI-Stream
    in_consumed = 1'b0;
    out_valid = 1'b0;
    out_last = 1'b0;
    out_data = 32'b00000000000000000000000000000000;
    t_0 = lane_up && channel_up;
    if ( ! t_0) begin
      tx_state_reg_temp = 2'b00;
    end
    case ( tx_state_reg_temp)
      2'b00 :
        begin
          if (lane_up && channel_up) begin
            tx_state_reg_temp = 2'b01;
            beat_cnt_next = 8'b00000000;
          end
        end
      2'b01 :
        begin
          if (in_valid && out_ready) begin
            out_data = in_data;
            out_valid = 1'b1;
            in_consumed = 1'b1;
            // ← сообщаем Input Buffer
            if (beat_cnt == (N1 - 8'b00000001)) begin
              tx_state_reg_temp = 2'b10;
              // beat_cnt = fi(0,0,beat_cnt.WordLength,0,fm);
            end
            else begin
              beat_cnt_next = beat_cnt + 8'b00000001;
            end
          end
        end
      default :
        begin
          // send last (D_WORD_rd_data)
          if (out_ready) begin
            // if out_ready && ~D_WORD_rd_empty % проверка empty
            out_data = {16'b0, D_WORD_rd_data};
            out_valid = 1'b1;
            out_last = 1'b1;
            // D_WORD_rd_en = true; % подтверждаем чтение
            tx_state_reg_temp = 2'b01;
            beat_cnt_next = 8'b00000000;
          end
        end
    endcase
    // ================= PUSH GENERATION =================
    // if out_valid
    //     push = true;
    //     push_data = out_data;
    //     push_last = out_last;
    // end
    // ================= FIFO READ (использует in_consumed!) =================
    D_FIFO_rd_en1 = ( ! D_FIFO_rd_empty) && (( ! in_valid) || in_consumed);
    // ================= INPUT BUFFER (перенесён после FSM) =================
    if (D_FIFO_rd_en1) begin
      in_data_next = D_FIFO_rd_data;
      in_valid_next = 1'b1;
    end
    else if (in_consumed) begin
      // Слово забрали в выходную очередь, но нового не загружено
      in_valid_next = 1'b0;
    end
    // ================= 2-WORD FIFO UPDATE =================
    // POP (shift)
    if (axis_fire && (out_cnt == 2'b10)) begin
      out_data0_next = out_data1;
      out_last0_next = out_last1;
    end
    if (out_valid) begin
      if (out_cnt == 2'b00) begin
        out_data0_next = out_data;
        out_last0_next = out_last;
      end
      else if (out_cnt == 2'b01) begin
        if (axis_fire) begin
          // Одновременный push и pop: новое слово идет сразу в out_data0
          out_data0_next = out_data;
          out_last0_next = out_last;
        end
        else begin
          out_data1_next = out_data;
          out_last1_next = out_last;
        end
      end
    end
    // COUNT UPDATE
    if (out_valid && ( ! axis_fire)) begin
      out_cnt_next = out_cnt + 2'b01;
    end
    else if (axis_fire && ( ! out_valid)) begin
      out_cnt_next = out_cnt - 2'b01;
    end
    // if (~(lane_up && channel_up))
    //     flow_ctrl_state(1) = 0;
    //     tx_state_reg(1) = 0;
    //     rx_state_reg(1) = 0;
    // end
    // 
    // if (s_axi_rx_snf)
    //     NFC_rcvd_value_reg = fi(s_axi_rx_fc_nb,0,NFC_rcvd_value_reg.WordLength,0,fm);
    // end
    // 
    // switch uint8(rx_state_reg)
    // 
    //     case 0
    //         if (s_axis_tvalid)
    //             rx_previous_reg = fi(s_axis_tdata, AXIS_nt, fm);
    //             rx_state_reg(1) = 1;
    //         else
    //             rx_state_reg(1) = 0;
    //         end
    // 
    //     otherwise
    //         if (s_axis_tvalid)
    //             if (s_axis_tdata~=fi(rx_previous_reg + 1, AXIS_nt, fm))
    //                 rx_err_r = true;
    //             end
    //             rx_previous_reg = fi(s_axis_tdata, AXIS_nt, fm);
    //         end
    // end
    // 
    // switch uint8(flow_ctrl_state)
    // 
    //     case 0
    // 
    //         if (lane_up && channel_up)
    //             flow_ctrl_state(1) = 1;
    //         else
    //             flow_ctrl_state(1) = 0;
    //         end
    // 
    //     case 1
    // 
    //         if (dbg_XOFF_xon) % DISABLE Link Partner
    //             axi_nfc_req_tmp = true;
    //             % axi_nfc_nb_reg = fi(dbg_NFC_NB_in,0,axi_nfc_nb_reg.WordLength,0,fm);
    //             axi_nfc_nb_reg = fi(bin2dec('1111'),0,axi_nfc_nb_reg.WordLength,0,fm);
    //             flow_ctrl_state(1) = 2;
    //         % else
    //         %     flow_ctrl_state(1) = flow_ctrl_state(1);
    //         end
    // 
    //     case 2
    //         if (m_axi_nfc_ack)
    //             axi_nfc_req_tmp = false;
    //             flow_ctrl_state(1) = 3;
    //         end
    // 
    //     case 3
    //         if (~dbg_XOFF_xon) % ENABLE Link Partner
    //             axi_nfc_req_tmp = true;
    //             % axi_nfc_nb_reg = fi(dbg_NFC_NB_in,0,axi_nfc_nb_reg.WordLength,0,fm);
    //             axi_nfc_nb_reg = fi(0,0,axi_nfc_nb_reg.WordLength,0,fm);
    //             flow_ctrl_state(1) = 4;
    //         % else
    //         %     flow_ctrl_state(1) = flow_ctrl_state(1);
    //         end
    // 
    //     otherwise
    //         if (m_axi_nfc_ack)
    //             axi_nfc_req_tmp = false;
    //             flow_ctrl_state(1) = 0;
    //         end
    // end
    m_axis_tdata = out_data0;
    m_axis_tvalid_1 = m_axis_tvalid;
    m_axis_tlast = out_last0;
    m_axis_tkeep = 4'b1111;
    m_axis_tuser = 1'b0;
    state = tx_state_reg;
    m_axi_nfc_req_1 = 1'b0;
    m_axi_nfc_nb_1 = 4'b0000;
    NFC_rcvd_value = 4'b0000;
    rx_err = rx_err_r;
    D_FIFO_rd_en_1 = D_FIFO_rd_en1;
    D_WORD_rd_en_1 = 1'b0;
    tx_state_reg_next = tx_state_reg_temp;
  end



  assign m_axi_tdata = m_axis_tdata;

  assign m_axi_tvalid = m_axis_tvalid_1;

  assign m_axi_tlast = m_axis_tlast;

  assign m_axi_tkeep = m_axis_tkeep;

  assign m_axi_tuser = m_axis_tuser;

  assign dbg_state_out = state;

  assign Zero_out1 = 1'b0;



  assign m_axi_nfc_req = Zero_out1;

  assign m_axi_nfc_nb = Zero_out1;

  assign dbg_NFC_rcvd_value = Zero_out1;

  assign dbg_rxerr_out = Zero_out1;

  assign D_FIFO_rd_en = D_FIFO_rd_en_1;

  assign D_WORD_rd_en = D_WORD_rd_en_1;

endmodule  // AXIS_master_FIFO_rd_2_WORD_FIFO

