// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\AXIS_master_FIFO_rd_reg_logic\AXIS_master_FIFO_rd_reg_logic.v
// Created: 2026-04-29 10:01:11
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: AXIS_master_FIFO_rd_reg_logic
// Source Path: AXIS_master_FIFO_rd_reg_logic
// Hierarchy Level: 0
// Model version: 16.421
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AXIS_master_FIFO_rd_reg_logic
          (clk,
           reset,
           lane_up,
           channel_up,
           m_axi_tready,
           s_axi_tdata,
           s_axi_tvalid,
           s_axi_tlast,
           s_axi_tkeep,
           s_axi_tuser,
           m_axi_nfc_ack,
           s_axi_rx_snf,
           s_axi_rx_fc_nb,
           LinkPartner_XOFF,
           dbg_NFC_NB_in,
           D_FIFO_rd_aempty,
           D_FIFO_rd_data,
           D_WORD_rd_empty,
           D_WORD_rd_data,
           D_FIFO_rd_empty,
           N,
           m_axi_tdata,
           m_axi_tvalid,
           m_axi_tlast,
           m_axi_tkeep,
           m_axi_tuser,
           dbg_state_out,
           m_axi_nfc_req,
           m_axi_nfc_nb,
           dbg_NFC_rcvd_value,
           dbg_rxerr_out,
           D_FIFO_rd_en,
           D_WORD_rd_en);


  input   clk;
  input   reset;
  input   lane_up;
  input   channel_up;
  input   m_axi_tready;
  input   [31:0] s_axi_tdata;  // uint32
  input   s_axi_tvalid;
  input   s_axi_tlast;
  input   [3:0] s_axi_tkeep;  // ufix4
  input   s_axi_tuser;
  input   m_axi_nfc_ack;
  input   s_axi_rx_snf;
  input   [3:0] s_axi_rx_fc_nb;  // ufix4
  input   LinkPartner_XOFF;
  input   [3:0] dbg_NFC_NB_in;  // ufix4
  input   D_FIFO_rd_aempty;
  input   [31:0] D_FIFO_rd_data;  // uint32
  input   D_WORD_rd_empty;
  input   [15:0] D_WORD_rd_data;  // uint16
  input   D_FIFO_rd_empty;
  input   [7:0] N;  // uint8
  output  [31:0] m_axi_tdata;  // uint32
  output  m_axi_tvalid;
  output  m_axi_tlast;
  output  [3:0] m_axi_tkeep;  // ufix4
  output  m_axi_tuser;
  output  [1:0] dbg_state_out;  // ufix2
  output  m_axi_nfc_req;
  output  m_axi_nfc_nb;
  output  dbg_NFC_rcvd_value;
  output  dbg_rxerr_out;
  output  D_FIFO_rd_en;
  output  D_WORD_rd_en;


  reg [31:0] m_axis_tdata;  // uint32
  reg  m_axis_tvalid;
  reg  m_axis_tlast;
  reg [3:0] m_axis_tkeep;  // ufix4
  reg  m_axis_tuser;
  reg [1:0] state;  // ufix2
  reg  D_FIFO_rd_en_1;
  reg  D_WORD_rd_en_1;
  reg [1:0] state_reg;  // ufix2
  reg [7:0] beat_cnt;  // ufix8
  reg [31:0] tdata_reg;  // ufix32
  reg  tvalid_reg;
  reg  tlast_reg;
  reg [1:0] state_reg_next;  // ufix2
  reg [7:0] beat_cnt_next;  // ufix8
  reg [31:0] tdata_reg_next;  // ufix32
  reg  tvalid_reg_next;
  reg  tlast_reg_next;
  wire Zero_out1;
  reg [7:0] N1;  // ufix8
  reg  accept;
  reg  can_load;


  always @(posedge clk or posedge reset)
    begin : opus_logic_bckp_process
      if (reset == 1'b1) begin
        state_reg <= 2'b00;
        beat_cnt <= 8'b00000000;
        tdata_reg <= 32'b00000000000000000000000000000000;
        tvalid_reg <= 1'b0;
        tlast_reg <= 1'b0;
      end
      else begin
        state_reg <= state_reg_next;
        beat_cnt <= beat_cnt_next;
        tdata_reg <= tdata_reg_next;
        tvalid_reg <= tvalid_reg_next;
        tlast_reg <= tlast_reg_next;
      end
    end

  always @(D_FIFO_rd_data, D_FIFO_rd_empty, D_WORD_rd_data, D_WORD_rd_empty, N, beat_cnt,
       channel_up, lane_up, m_axi_tready, state_reg, tdata_reg, tlast_reg,
       tvalid_reg) begin
    state_reg_next = state_reg;
    beat_cnt_next = beat_cnt;
    tdata_reg_next = tdata_reg;
    tvalid_reg_next = tvalid_reg;
    tlast_reg_next = tlast_reg;
    // FSM: чтение из FWFT FIFO -> AXIS с формированием TLAST каждые (N+1) beat'ов.
    // ---------------- Параметр пакета ----------------
    N1 = N;
    // количество слов из D_FIFO до вставки D_WORD с TLAST
    // ---------------- Регистры (persistent) ----------
    // ---------------- Выходы ------------------------
    // 8 байт валидны (для 64-бит шины)
    // ---------------- Значения по умолчанию ----------
    D_FIFO_rd_en_1 = 1'b0;
    D_WORD_rd_en_1 = 1'b0;
    // Слот выходного регистра свободен, если:
    //   - он сейчас не содержит valid-beat, ИЛИ
    //   - текущий beat принят получателем (tvalid && tready).
    accept = tvalid_reg && m_axi_tready;
    can_load = ( ! tvalid_reg) || accept;
    // Предустановки next-state
    // next_state  = state_reg;
    // next_beat   = beat_cnt;
    // next_tdata  = tdata_reg;
    // next_tvalid = tvalid_reg;
    // next_tlast  = tlast_reg;
    // Если beat принят — снимаем valid/last (могут быть переписаны ниже при загрузке)
    if (accept) begin
      tvalid_reg_next = 1'b0;
      tlast_reg_next = 1'b0;
    end
    // ---------------- Логика состояний ---------------
    case ( state_reg)
      2'b00 :
        begin
          // IDLE
          if (channel_up && lane_up) begin
            state_reg_next = 2'b01;
            beat_cnt_next = 8'b00000000;
          end
        end
      2'b01 :
        begin
          // STREAM: читаем данные из D_FIFO
          if (can_load && ( ! D_FIFO_rd_empty)) begin
            D_FIFO_rd_en_1 = 1'b1;
            // подтверждаем чтение FWFT
            tdata_reg_next = D_FIFO_rd_data;
            // защёлкиваем то же слово
            tvalid_reg_next = 1'b1;
            tlast_reg_next = 1'b0;
            if (beat_cnt == (N1 - 8'b00000001)) begin
              beat_cnt_next = 8'b00000000;
              state_reg_next = 2'b10;
              // следующий beat — D_WORD+TLAST
            end
            else begin
              beat_cnt_next = beat_cnt + 8'b00000001;
            end
          end
        end
      2'b10 :
        begin
          // SEND LAST: одно слово из D_WORD с TLAST
          if (can_load && ( ! D_WORD_rd_empty)) begin
            D_WORD_rd_en_1 = 1'b1;
            tdata_reg_next = {16'b0, D_WORD_rd_data};
            tvalid_reg_next = 1'b1;
            tlast_reg_next = 1'b1;
            state_reg_next = 2'b01;
          end
        end
      default :
        begin
          state_reg_next = 2'b00;
        end
    endcase
    // ---------------- Обновление регистров -----------
    // state_reg  = next_state;
    // beat_cnt   = next_beat;
    // tdata_reg  = next_tdata;
    // tvalid_reg = next_tvalid;
    // tlast_reg  = next_tlast;
    m_axis_tdata = tdata_reg;
    m_axis_tvalid = tvalid_reg;
    m_axis_tlast = tlast_reg;
    m_axis_tkeep = 4'b1111;
    m_axis_tuser = 1'b0;
    state = state_reg;
  end



  assign m_axi_tdata = m_axis_tdata;

  assign m_axi_tvalid = m_axis_tvalid;

  assign m_axi_tlast = m_axis_tlast;

  assign m_axi_tkeep = m_axis_tkeep;

  assign m_axi_tuser = m_axis_tuser;

  assign dbg_state_out = state;

  assign Zero_out1 = 1'b0;



  assign m_axi_nfc_req = Zero_out1;

  assign m_axi_nfc_nb = Zero_out1;

  assign dbg_NFC_rcvd_value = Zero_out1;

  assign dbg_rxerr_out = Zero_out1;

  assign D_FIFO_rd_en = D_FIFO_rd_en_1;

  assign D_WORD_rd_en = D_WORD_rd_en_1;

endmodule  // AXIS_master_FIFO_rd_reg_logic

