// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\simple_tdata_checker\simple_tdata_checker.v
// Created: 2026-04-29 09:02:11
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simple_tdata_checker
// Source Path: simple_tdata_checker
// Hierarchy Level: 0
// Model version: 16.261
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simple_tdata_checker
          (clk,
           reset,
           m_axis_tready,
           m_axis_tdata,
           m_axis_tvalid,
           m_axis_tlast,
           N,
           err_out);


  input   clk;
  input   reset;
  input   m_axis_tready;
  input   [31:0] m_axis_tdata;  // uint32
  input   m_axis_tvalid;
  input   m_axis_tlast;
  input   [7:0] N;  // uint8
  output  err_out;


  reg  err_out_1;
  reg [7:0] cnt;  // ufix8
  reg [7:0] beat_cnt;  // ufix8
  reg [7:0] cnt_next;  // ufix8
  reg [7:0] beat_cnt_next;  // ufix8


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        cnt <= 8'b00000000;
        beat_cnt <= 8'b00000000;
      end
      else begin
        cnt <= cnt_next;
        beat_cnt <= beat_cnt_next;
      end
    end

  always @(N, beat_cnt, cnt, m_axis_tdata, m_axis_tlast, m_axis_tready, m_axis_tvalid) begin
    cnt_next = cnt;
    beat_cnt_next = beat_cnt;
    // Регистры
    if (m_axis_tready && m_axis_tvalid) begin
      if (beat_cnt != N) begin
        err_out_1 = (m_axis_tdata != {24'b0, cnt}) || m_axis_tlast;
        beat_cnt_next = beat_cnt + 8'b00000001;
        cnt_next = cnt + 8'b00000001;
      end
      else begin
        // cnt==N
        err_out_1 =  ! m_axis_tlast;
        beat_cnt_next = 8'b00000000;
      end
      // cnt = fi(cnt + 1, nt, fm);
    end
    else begin
      err_out_1 = 1'b0;
    end
  end



  assign err_out = err_out_1;

endmodule  // simple_tdata_checker

