// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\simple_FIFO_rd_check\simple_FIFO_rd_check.v
// Created: 2026-04-24 15:48:10
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simple_FIFO_rd_check
// Source Path: simple_FIFO_rd_check
// Hierarchy Level: 0
// Model version: 16.255
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simple_FIFO_rd_check
          (clk,
           reset,
           fifo_wr_done,
           fifo_rd_en,
           fifo_rd_done);


  input   clk;
  input   reset;
  input   fifo_wr_done;
  output  fifo_rd_en;
  output  fifo_rd_done;


  reg  [1:0] Delay16_reg;  // ufix1 [2]
  wire Delay16_out1;
  reg [15:0] fifo_wr_data;  // uint16
  reg  fifo_wr_en;
  reg  fifo_rd_en_1;
  reg  fifo_rd_done_1;
  reg [15:0] cnt;  // ufix16
  reg [1:0] states;  // ufix2
  reg [15:0] cnt_next;  // ufix16
  reg [1:0] states_next;  // ufix2


  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_reg <= {2{1'b0}};
      end
      else begin
        Delay16_reg[0] <= fifo_wr_done;
        Delay16_reg[1] <= Delay16_reg[0];
      end
    end

  assign Delay16_out1 = Delay16_reg[1];



  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        cnt <= 16'b0000000000000000;
        states <= 2'b00;
      end
      else begin
        cnt <= cnt_next;
        states <= states_next;
      end
    end

  always @(Delay16_out1, cnt, states) begin
    cnt_next = cnt;
    states_next = states;
    // Регистры
    fifo_rd_en_1 = 1'b0;
    fifo_rd_done_1 = 1'b0;
    case ( states)
      2'b00 :
        begin
          if (Delay16_out1) begin
            // cnt = fi(cnt+1,nt,fm);
            states_next = 2'b10;
            // else
            //     % cnt = fi(0,nt,fm);
            //     states(1) = 1;
          end
          // case 1
          //     if (cnt<16)
          //         fifo_wr_data = fi(cnt,nt,fm);
          //         fifo_wr_en = true;
          //         cnt = fi(cnt+1,nt,fm);
          //         % states(1) = 0;
          //     else
          //         cnt = fi(0,nt,fm);
          //         states(1) = 2;
          //     end
        end
      2'b10 :
        begin
          if (cnt < 16'b0000000000010000) begin
            fifo_rd_en_1 = 1'b1;
            cnt_next = cnt + 16'b0000000000000001;
            // states(1) = 1;
          end
          else begin
            cnt_next = 16'b0000000000000000;
            states_next = 2'b11;
          end
        end
      default :
        begin
          // null
          fifo_rd_done_1 = 1'b1;
        end
    endcase
    fifo_wr_data = 16'b0000000000000000;
    fifo_wr_en = 1'b0;
  end



  assign fifo_rd_en = fifo_rd_en_1;

  assign fifo_rd_done = fifo_rd_done_1;

endmodule  // simple_FIFO_rd_check

