// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\Simple_AXIS_master\Simple_AXIS_master.v
// Created: 2026-04-20 16:43:13
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Simple_AXIS_master
// Source Path: Simple_AXIS_master
// Hierarchy Level: 0
// Model version: 16.222
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Simple_AXIS_master
          (clk,
           reset,
           lane_up,
           channel_up,
           m_axi_tready,
           s_axi_tdata,
           s_axi_tvalid,
           s_axi_tlast,
           s_axi_tkeep,
           s_axi_tuser,
           m_axi_nfc_ack,
           s_axi_rx_snf,
           s_axi_rx_fc_nb,
           LinkPartner_XOFF,
           dbg_NFC_NB_in,
           m_axi_tdata,
           m_axi_tvalid,
           m_axi_tlast,
           m_axi_tkeep,
           m_axi_tuser,
           dbg_state_out,
           m_axi_nfc_req,
           m_axi_nfc_nb,
           dbg_NFC_rcvd_value,
           dbg_rxerr_out);


  input   clk;
  input   reset;
  input   lane_up;
  input   channel_up;
  input   m_axi_tready;
  input   [31:0] s_axi_tdata;  // uint32
  input   s_axi_tvalid;
  input   s_axi_tlast;
  input   [3:0] s_axi_tkeep;  // ufix4
  input   s_axi_tuser;
  input   m_axi_nfc_ack;
  input   s_axi_rx_snf;
  input   [3:0] s_axi_rx_fc_nb;  // ufix4
  input   LinkPartner_XOFF;
  input   [3:0] dbg_NFC_NB_in;  // ufix4
  output  [31:0] m_axi_tdata;  // uint32
  output  m_axi_tvalid;
  output  m_axi_tlast;
  output  [3:0] m_axi_tkeep;  // ufix4
  output  m_axi_tuser;
  output  [1:0] dbg_state_out;  // ufix2
  output  m_axi_nfc_req;
  output  [3:0] m_axi_nfc_nb;  // ufix4
  output  [3:0] dbg_NFC_rcvd_value;  // ufix4
  output  dbg_rxerr_out;


  reg [31:0] m_axis_tdata;  // uint32
  reg  m_axis_tvalid;
  reg  m_axis_tlast;
  reg [3:0] m_axis_tkeep;  // ufix4
  reg  m_axis_tuser;
  reg [1:0] state;  // ufix2
  reg  m_axi_nfc_req_1;
  reg [3:0] m_axi_nfc_nb_1;  // ufix4
  reg [3:0] NFC_rcvd_value;  // ufix4
  reg  rx_err;
  reg [1:0] tx_state_reg;  // ufix2
  reg [1:0] rx_state_reg;  // ufix2
  reg [2:0] flow_ctrl_state;  // ufix3
  reg  axi_nfc_req_tmp;
  reg [3:0] axi_nfc_nb_reg;  // ufix4
  reg [3:0] NFC_rcvd_value_reg;  // ufix4
  reg [31:0] counter_reg;  // ufix32
  reg [10:0] data_counter_reg;  // ufix11
  reg [31:0] m_axis_tdata_reg;  // ufix32
  reg [3:0] m_axis_tkeep_reg;  // ufix4
  reg  m_axis_tready_int_reg;
  reg  m_axis_tvalid_reg;
  reg  temp_m_axis_tvalid_reg;
  reg  temp_m_axis_tlast_reg;
  reg  temp_m_axis_tuser_reg;
  reg [31:0] temp_m_axis_tdata_reg;  // ufix32
  reg [3:0] temp_m_axis_tkeep_reg;  // ufix4
  reg  m_axis_tlast_reg;
  reg  m_axis_tuser_reg;
  reg [31:0] rx_previous_reg;  // ufix32
  reg  rx_err_r;
  reg [1:0] tx_state_reg_next;  // ufix2
  reg [1:0] rx_state_reg_next;  // ufix2
  reg [2:0] flow_ctrl_state_next;  // ufix3
  reg  axi_nfc_req_tmp_next;
  reg [3:0] axi_nfc_nb_reg_next;  // ufix4
  reg [3:0] NFC_rcvd_value_reg_next;  // ufix4
  reg [31:0] counter_reg_next;  // ufix32
  reg [10:0] data_counter_reg_next;  // ufix11
  reg [31:0] m_axis_tdata_reg_next;  // ufix32
  reg [3:0] m_axis_tkeep_reg_next;  // ufix4
  reg  m_axis_tready_int_reg_next;
  reg  m_axis_tvalid_reg_next;
  reg  temp_m_axis_tvalid_reg_next;
  reg  temp_m_axis_tlast_reg_next;
  reg  temp_m_axis_tuser_reg_next;
  reg [31:0] temp_m_axis_tdata_reg_next;  // ufix32
  reg [3:0] temp_m_axis_tkeep_reg_next;  // ufix4
  reg  m_axis_tlast_reg_next;
  reg  m_axis_tuser_reg_next;
  reg [31:0] rx_previous_reg_next;  // ufix32
  reg  rx_err_r_next;
  reg [31:0] m_axis_tdata_int;  // ufix32
  reg  m_axis_tvalid_int;
  reg  m_axis_tlast_int;
  reg  store_axis_int_to_output;
  reg  store_axis_int_to_temp;
  reg  store_axis_temp_to_output;
  reg  t_0;
  reg [1:0] tx_state_reg_temp;  // ufix2
  reg [1:0] rx_state_reg_temp;  // ufix2
  reg [2:0] flow_ctrl_state_temp;  // ufix3


  always @(posedge clk or posedge reset)
    begin : some_logic_process
      if (reset == 1'b1) begin
        tx_state_reg <= 2'b00;
        rx_state_reg <= 2'b00;
        flow_ctrl_state <= 3'b000;
        axi_nfc_req_tmp <= 1'b0;
        axi_nfc_nb_reg <= 4'b0000;
        NFC_rcvd_value_reg <= 4'b0000;
        counter_reg <= 32'b00000000000000000000000000000000;
        data_counter_reg <= 11'b00000000000;
        m_axis_tdata_reg <= 32'b00000000000000000000000000000000;
        m_axis_tkeep_reg <= 4'b0000;
        m_axis_tready_int_reg <= 1'b0;
        m_axis_tvalid_reg <= 1'b0;
        temp_m_axis_tvalid_reg <= 1'b0;
        temp_m_axis_tlast_reg <= 1'b0;
        temp_m_axis_tuser_reg <= 1'b0;
        temp_m_axis_tdata_reg <= 32'b00000000000000000000000000000000;
        temp_m_axis_tkeep_reg <= 4'b0000;
        m_axis_tlast_reg <= 1'b0;
        m_axis_tuser_reg <= 1'b0;
        rx_previous_reg <= 32'b00000000000000000000000000000000;
        rx_err_r <= 1'b0;
      end
      else begin
        tx_state_reg <= tx_state_reg_next;
        rx_state_reg <= rx_state_reg_next;
        flow_ctrl_state <= flow_ctrl_state_next;
        axi_nfc_req_tmp <= axi_nfc_req_tmp_next;
        axi_nfc_nb_reg <= axi_nfc_nb_reg_next;
        NFC_rcvd_value_reg <= NFC_rcvd_value_reg_next;
        counter_reg <= counter_reg_next;
        data_counter_reg <= data_counter_reg_next;
        m_axis_tdata_reg <= m_axis_tdata_reg_next;
        m_axis_tkeep_reg <= m_axis_tkeep_reg_next;
        m_axis_tready_int_reg <= m_axis_tready_int_reg_next;
        m_axis_tvalid_reg <= m_axis_tvalid_reg_next;
        temp_m_axis_tvalid_reg <= temp_m_axis_tvalid_reg_next;
        temp_m_axis_tlast_reg <= temp_m_axis_tlast_reg_next;
        temp_m_axis_tuser_reg <= temp_m_axis_tuser_reg_next;
        temp_m_axis_tdata_reg <= temp_m_axis_tdata_reg_next;
        temp_m_axis_tkeep_reg <= temp_m_axis_tkeep_reg_next;
        m_axis_tlast_reg <= m_axis_tlast_reg_next;
        m_axis_tuser_reg <= m_axis_tuser_reg_next;
        rx_previous_reg <= rx_previous_reg_next;
        rx_err_r <= rx_err_r_next;
      end
    end

  always @(LinkPartner_XOFF, NFC_rcvd_value_reg, axi_nfc_nb_reg, axi_nfc_req_tmp,
       channel_up, counter_reg, data_counter_reg, flow_ctrl_state, lane_up,
       m_axi_nfc_ack, m_axi_tready, m_axis_tdata_reg, m_axis_tkeep_reg,
       m_axis_tlast_reg, m_axis_tready_int_reg, m_axis_tuser_reg,
       m_axis_tvalid_reg, rx_err_r, rx_previous_reg, rx_state_reg,
       s_axi_rx_fc_nb, s_axi_rx_snf, s_axi_tdata, s_axi_tvalid,
       temp_m_axis_tdata_reg, temp_m_axis_tkeep_reg, temp_m_axis_tlast_reg,
       temp_m_axis_tuser_reg, temp_m_axis_tvalid_reg, tx_state_reg) begin
    tx_state_reg_temp = tx_state_reg;
    rx_state_reg_temp = rx_state_reg;
    flow_ctrl_state_temp = flow_ctrl_state;
    axi_nfc_req_tmp_next = axi_nfc_req_tmp;
    axi_nfc_nb_reg_next = axi_nfc_nb_reg;
    NFC_rcvd_value_reg_next = NFC_rcvd_value_reg;
    counter_reg_next = counter_reg;
    data_counter_reg_next = data_counter_reg;
    m_axis_tdata_reg_next = m_axis_tdata_reg;
    m_axis_tkeep_reg_next = m_axis_tkeep_reg;
    m_axis_tvalid_reg_next = m_axis_tvalid_reg;
    temp_m_axis_tvalid_reg_next = temp_m_axis_tvalid_reg;
    temp_m_axis_tlast_reg_next = temp_m_axis_tlast_reg;
    temp_m_axis_tuser_reg_next = temp_m_axis_tuser_reg;
    temp_m_axis_tdata_reg_next = temp_m_axis_tdata_reg;
    temp_m_axis_tkeep_reg_next = temp_m_axis_tkeep_reg;
    m_axis_tlast_reg_next = m_axis_tlast_reg;
    m_axis_tuser_reg_next = m_axis_tuser_reg;
    rx_previous_reg_next = rx_previous_reg;
    // enable ready input next cycle if output is ready or if both output registers are empty
    m_axis_tready_int_reg_next = m_axi_tready || (( ! temp_m_axis_tvalid_reg) && ( ! m_axis_tvalid_reg));
    m_axis_tdata_int = 32'b00000000000000000000000000000000;
    m_axis_tvalid_int = 1'b0;
    m_axis_tlast_int = 1'b0;
    rx_err_r_next = 1'b0;
    t_0 = lane_up && channel_up;
    if ( ! t_0) begin
      flow_ctrl_state_temp = 3'b000;
      tx_state_reg_temp = 2'b00;
      rx_state_reg_temp = 2'b00;
    end
    if (s_axi_rx_snf) begin
      NFC_rcvd_value_reg_next = s_axi_rx_fc_nb;
    end
    case ( rx_state_reg_temp)
      2'b00 :
        begin
          if (s_axi_tvalid) begin
            rx_previous_reg_next = s_axi_tdata;
            rx_state_reg_temp = 2'b01;
          end
          else begin
            rx_state_reg_temp = 2'b00;
          end
        end
      default :
        begin
          if (s_axi_tvalid) begin
            if (s_axi_tdata != (rx_previous_reg + 32'b00000000000000000000000000000001)) begin
              rx_err_r_next = 1'b1;
            end
            rx_previous_reg_next = s_axi_tdata;
          end
        end
    endcase
    case ( flow_ctrl_state_temp)
      3'b000 :
        begin
          if (lane_up && channel_up) begin
            flow_ctrl_state_temp = 3'b001;
          end
          else begin
            flow_ctrl_state_temp = 3'b000;
          end
        end
      3'b001 :
        begin
          if (LinkPartner_XOFF) begin
            // DISABLE Link Partner
            axi_nfc_req_tmp_next = 1'b1;
            // axi_nfc_nb_reg = fi(dbg_NFC_NB_in,0,axi_nfc_nb_reg.WordLength,0,fm);
            axi_nfc_nb_reg_next = 4'b1111;
            flow_ctrl_state_temp = 3'b010;
            // else
            //     flow_ctrl_state(1) = flow_ctrl_state(1);
          end
        end
      3'b010 :
        begin
          if (m_axi_nfc_ack) begin
            axi_nfc_req_tmp_next = 1'b0;
            flow_ctrl_state_temp = 3'b011;
          end
        end
      3'b011 :
        begin
          if ( ! LinkPartner_XOFF) begin
            // ENABLE Link Partner
            axi_nfc_req_tmp_next = 1'b1;
            // axi_nfc_nb_reg = fi(dbg_NFC_NB_in,0,axi_nfc_nb_reg.WordLength,0,fm);
            axi_nfc_nb_reg_next = 4'b0000;
            flow_ctrl_state_temp = 3'b100;
            // else
            //     flow_ctrl_state(1) = flow_ctrl_state(1);
          end
        end
      default :
        begin
          if (m_axi_nfc_ack) begin
            axi_nfc_req_tmp_next = 1'b0;
            flow_ctrl_state_temp = 3'b000;
          end
        end
    endcase
    case ( tx_state_reg_temp)
      2'b00 :
        begin
          if (lane_up && channel_up) begin
            tx_state_reg_temp = 2'b01;
            counter_reg_next = 32'b00000000000000000000000000000000;
            data_counter_reg_next = 11'b00000000000;
          end
          else begin
            tx_state_reg_temp = 2'b00;
          end
        end
      2'b01 :
        begin
          if (m_axis_tready_int_reg) begin
            m_axis_tdata_int = counter_reg;
            m_axis_tvalid_int = 1'b1;
            tx_state_reg_temp = 2'b01;
            if (data_counter_reg == 11'b00111110100) begin
              // tx_state_reg(1) = 2;
              m_axis_tlast_int = 1'b1;
              // m_axis_tkeep_int = fi(bin2dec('0001'),0,m_axis_tkeep_reg.WordLength,0,fm);
              data_counter_reg_next = 11'b00000000000;
            end
            else begin
              data_counter_reg_next = data_counter_reg + 11'b00000000001;
            end
            counter_reg_next = counter_reg + 32'b00000000000000000000000000000001;
          end
        end
      default :
        begin
          // dummy state for "some pause"
          tx_state_reg_temp = 2'b00;
        end
    endcase
    store_axis_int_to_output = 1'b0;
    store_axis_int_to_temp = 1'b0;
    store_axis_temp_to_output = 1'b0;
    if (m_axis_tready_int_reg) begin
      // input is ready
      if (m_axi_tready || ( ! m_axis_tvalid_reg)) begin
        // output is ready or currently not valid, transfer data to output
        // m_axis_tvalid_next = m_axis_tvalid_int; % m_axis_tvalid_reg = m_axis_tvalid_int;
        m_axis_tvalid_reg_next = m_axis_tvalid_int;
        store_axis_int_to_output = 1'b1;
      end
      else begin
        // output is not ready, store input in temp
        // temp_m_axis_tvalid_next = m_axis_tvalid_int; % temp_m_axis_tvalid_reg = m_axis_tvalid_int;
        temp_m_axis_tvalid_reg_next = m_axis_tvalid_int;
        store_axis_int_to_temp = 1'b1;
      end
    end
    else if (m_axi_tready) begin
      // input is not ready, but output is ready
      // m_axis_tvalid_next = temp_m_axis_tvalid_reg; % m_axis_tvalid_reg = temp_m_axis_tvalid_reg;
      m_axis_tvalid_reg_next = temp_m_axis_tvalid_reg;
      // temp_m_axis_tvalid_next = false; % temp_m_axis_tvalid_reg = false;
      temp_m_axis_tvalid_reg_next = 1'b0;
      store_axis_temp_to_output = 1'b1;
    end
    // m_axis_tvalid_reg = m_axis_tvalid_next;
    // temp_m_axis_tvalid_reg = temp_m_axis_tvalid_next;
    if (store_axis_int_to_output) begin
      m_axis_tdata_reg_next = m_axis_tdata_int;
      m_axis_tkeep_reg_next = 4'b1111;
      m_axis_tlast_reg_next = m_axis_tlast_int;
      m_axis_tuser_reg_next = 1'b0;
    end
    else if (store_axis_temp_to_output) begin
      m_axis_tdata_reg_next = temp_m_axis_tdata_reg;
      m_axis_tkeep_reg_next = temp_m_axis_tkeep_reg;
      m_axis_tlast_reg_next = temp_m_axis_tlast_reg;
      m_axis_tuser_reg_next = temp_m_axis_tuser_reg;
    end
    if (store_axis_int_to_temp) begin
      temp_m_axis_tdata_reg_next = m_axis_tdata_int;
      temp_m_axis_tkeep_reg_next = 4'b1111;
      temp_m_axis_tlast_reg_next = m_axis_tlast_int;
      temp_m_axis_tuser_reg_next = 1'b0;
    end
    // % rd_addr = rd_addr_reg; % 1 cycle "rd_addr" change to "rd_dout" change
    // rd_addr = bitsliceget(rd_addr_reg,rd_addr_reg.WordLength,5);
    // m_axis_tdata = m_axis_tdata_reg;
    // m_axis_tkeep = m_axis_tkeep_reg;
    // m_axis_tvalid = m_axis_tvalid_reg;
    // m_axis_tlast = m_axis_tlast_reg;
    // m_axis_tuser = m_axis_tuser_reg;
    m_axis_tdata = m_axis_tdata_reg;
    m_axis_tvalid = m_axis_tvalid_reg;
    m_axis_tlast = m_axis_tlast_reg;
    m_axis_tkeep = m_axis_tkeep_reg;
    m_axis_tuser = m_axis_tuser_reg;
    state = tx_state_reg;
    m_axi_nfc_req_1 = axi_nfc_req_tmp;
    m_axi_nfc_nb_1 = axi_nfc_nb_reg;
    NFC_rcvd_value = NFC_rcvd_value_reg;
    rx_err = rx_err_r;
    tx_state_reg_next = tx_state_reg_temp;
    rx_state_reg_next = rx_state_reg_temp;
    flow_ctrl_state_next = flow_ctrl_state_temp;
  end



  assign m_axi_tdata = m_axis_tdata;

  assign m_axi_tvalid = m_axis_tvalid;

  assign m_axi_tlast = m_axis_tlast;

  assign m_axi_tkeep = m_axis_tkeep;

  assign m_axi_tuser = m_axis_tuser;

  assign dbg_state_out = state;

  assign dbg_NFC_rcvd_value = NFC_rcvd_value;

  assign dbg_rxerr_out = rx_err;

  assign m_axi_nfc_req = m_axi_nfc_req_1;

  assign m_axi_nfc_nb = m_axi_nfc_nb_1;

endmodule  // Simple_AXIS_master

