// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\Simple_tready_gen\Simple_tready_gen.v
// Created: 2026-04-23 09:15:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Simple_tready_gen
// Source Path: Simple_tready_gen
// Hierarchy Level: 0
// Model version: 16.232
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Simple_tready_gen
          (clk,
           reset,
           tvalid,
           tready);


  input   clk;
  input   reset;
  input   tvalid;
  output  tready;


  reg [7:0] HDL_Counter_out1;  // uint8
  wire [7:0] count;  // uint8
  wire need_to_wrap;
  wire [7:0] count_value;  // uint8
  wire [7:0] count_1;  // uint8
  wire Compare_To_Constant_out1;
  wire Compare_To_Constant1_out1;
  wire OR_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10
  assign count = HDL_Counter_out1 + 8'b00000001;



  assign need_to_wrap = HDL_Counter_out1 == 8'b00001010;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              8'b00000000);



  assign count_1 = (tvalid == 1'b0 ? HDL_Counter_out1 :
              count_value);



  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 8'b00000000;
      end
      else begin
        HDL_Counter_out1 <= count_1;
      end
    end



  assign Compare_To_Constant_out1 = HDL_Counter_out1 < 8'b00000011;



  assign Compare_To_Constant1_out1 = HDL_Counter_out1 > 8'b00000111;



  assign OR_out1 = Compare_To_Constant_out1 | Compare_To_Constant1_out1;



  assign tready = OR_out1;

endmodule  // Simple_tready_gen

