// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\simple_FIFO_rd_axis_master_2skidbufs\simple_FIFO_rd_axis_master_2skidbufs.v
// Created: 2026-04-23 14:18:02
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simple_FIFO_rd_axis_master_2skidbufs
// Source Path: simple_FIFO_rd_axis_master_2skidbufs
// Hierarchy Level: 0
// Model version: 16.242
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simple_FIFO_rd_axis_master_2skidbufs
          (clk,
           reset,
           m_axis_tready,
           fifo_empty,
           fifo_data,
           m_axis_tdata,
           m_axis_tvalid,
           m_axis_tlast,
           fifo_rd_en);


  input   clk;
  input   reset;
  input   m_axis_tready;
  input   fifo_empty;
  input   [15:0] fifo_data;  // uint16
  output  [15:0] m_axis_tdata;  // uint16
  output  m_axis_tvalid;
  output  m_axis_tlast;
  output  fifo_rd_en;


  reg [15:0] m_axis_tdata_1;  // uint16
  reg  m_axis_tvalid_1;
  reg  m_axis_tlast_1;
  reg  fifo_rd_en_1;
  reg  v0;
  reg [15:0] d0;  // ufix16
  reg  v1;
  reg [15:0] d1;  // ufix16
  reg  v0_next;
  reg [15:0] d0_next;  // ufix16
  reg  v1_next;
  reg [15:0] d1_next;  // ufix16
  reg  take1;
  reg  move;
  reg  take0;


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        v0 <= 1'b0;
        d0 <= 16'b0000000000000000;
        v1 <= 1'b0;
        d1 <= 16'b0000000000000000;
      end
      else begin
        v0 <= v0_next;
        d0 <= d0_next;
        v1 <= v1_next;
        d1 <= d1_next;
      end
    end

  always @(d0, d1, fifo_data, fifo_empty, m_axis_tready, v0, v1) begin
    v0_next = v0;
    d0_next = d0;
    v1_next = v1;
    d1_next = d1;
    // Регистры
    // ------------------------------------------------------------
    // AXI outputs
    // ------------------------------------------------------------
    // ------------------------------------------------------------
    // Control signals
    // ------------------------------------------------------------
    // AXI handshake:
    take1 = v1 && m_axis_tready;
    // stage1 can move if empty or being consumed:
    move = ( ! v1) || take1;
    // stage1 can accept data
    // stage0 gives data when it has valid and stage1 can accept:
    take0 = v0 && move;
    // stage0 -> stage1 transfer
    // ------------------------------------------------------------
    // FIFO read enable
    // ------------------------------------------------------------
    fifo_rd_en_1 = (( ! v0) || take0) && ( ! fifo_empty);
    // -------------------------
    // Stage 1 (AXI side)
    // -------------------------
    if (move) begin
      v1_next = v0;
      d1_next = d0;
    end
    // -------------------------
    // Stage 0 (FIFO side)
    // -------------------------
    if (( ! v0) || take0) begin
      if ( ! fifo_empty) begin
        v0_next = 1'b1;
        d0_next = fifo_data;
      end
      else begin
        v0_next = 1'b0;
      end
    end
    m_axis_tdata_1 = d1;
    m_axis_tvalid_1 = v1;
    m_axis_tlast_1 = 1'b0;
  end



  assign m_axis_tdata = m_axis_tdata_1;

  assign m_axis_tvalid = m_axis_tvalid_1;

  assign m_axis_tlast = m_axis_tlast_1;

  assign fifo_rd_en = fifo_rd_en_1;

endmodule  // simple_FIFO_rd_axis_master_2skidbufs

