// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\simple_FIFO_wr_check\simple_FIFO_wr_check.v
// Created: 2026-04-24 15:38:12
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simple_FIFO_wr_check
// Source Path: simple_FIFO_wr_check
// Hierarchy Level: 0
// Model version: 16.252
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simple_FIFO_wr_check
          (clk,
           reset,
           fifo_wr_data,
           fifo_wr_en,
           fifo_rd_en,
           fifo_wr_done);


  input   clk;
  input   reset;
  output  [15:0] fifo_wr_data;  // uint16
  output  fifo_wr_en;
  output  fifo_rd_en;
  output  fifo_wr_done;


  reg [15:0] fifo_wr_data_1;  // uint16
  reg  fifo_wr_en_1;
  reg  fifo_rd_en_1;
  reg  fifo_wr_done_1;
  reg [15:0] cnt;  // ufix16
  reg [1:0] states;  // ufix2
  reg [15:0] cnt_next;  // ufix16
  reg [1:0] states_next;  // ufix2


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        cnt <= 16'b0000000000000000;
        states <= 2'b00;
      end
      else begin
        cnt <= cnt_next;
        states <= states_next;
      end
    end

  always @(cnt, states) begin
    cnt_next = cnt;
    states_next = states;
    // Регистры
    fifo_wr_en_1 = 1'b0;
    fifo_wr_done_1 = 1'b0;
    fifo_wr_data_1 = 16'b0000000000000000;
    case ( states)
      2'b00 :
        begin
          if (cnt < 16'b0000000000000011) begin
            cnt_next = cnt + 16'b0000000000000001;
            states_next = 2'b00;
          end
          else begin
            cnt_next = 16'b0000000000000000;
            states_next = 2'b01;
          end
        end
      2'b01 :
        begin
          if (cnt < 16'b0000000000010000) begin
            fifo_wr_data_1 = cnt;
            fifo_wr_en_1 = 1'b1;
            cnt_next = cnt + 16'b0000000000000001;
            // states(1) = 0;
          end
          else begin
            cnt_next = 16'b0000000000000000;
            states_next = 2'b11;
          end
          // case 2
          //     if (cnt<16)
          //         fifo_rd_en = true;
          //         cnt = fi(cnt+1,nt,fm);
          //         % states(1) = 1;
          //     else
          //         cnt = fi(0,nt,fm);
          //         states(1) = 3;
          //     end
        end
      default :
        begin
          // null
          fifo_wr_done_1 = 1'b1;
        end
    endcase
    fifo_rd_en_1 = 1'b0;
  end



  assign fifo_wr_data = fifo_wr_data_1;

  assign fifo_wr_en = fifo_wr_en_1;

  assign fifo_rd_en = fifo_rd_en_1;

  assign fifo_wr_done = fifo_wr_done_1;

endmodule  // simple_FIFO_wr_check

