// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\Simple_avalon_rdy_gen\Simple_avalon_rdy_gen.v
// Created: 2026-04-30 12:28:47
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Simple_avalon_rdy_gen
// Source Path: Simple_avalon_rdy_gen
// Hierarchy Level: 0
// Model version: 16.264
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Simple_avalon_rdy_gen
          (clk,
           reset,
           tvalid,
           tready);


  input   clk;
  input   reset;
  input   tvalid;
  output  tready;


  reg  tready_1;
  reg [7:0] cnt;  // ufix8
  reg [1:0] states;  // ufix2
  reg  toggle;
  reg [7:0] cnt_next;  // ufix8
  reg [1:0] states_next;  // ufix2
  reg  toggle_next;
  reg [7:0] cnt_HIGH_MAX;  // ufix8
  reg [7:0] cnt_LOW_MAX;  // ufix8


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        cnt <= 8'b00000000;
        states <= 2'b00;
        toggle <= 1'b0;
      end
      else begin
        cnt <= cnt_next;
        states <= states_next;
        toggle <= toggle_next;
      end
    end

  always @(cnt, states, toggle, tvalid) begin
    cnt_next = cnt;
    states_next = states;
    toggle_next = toggle;
    // Регистры
    tready_1 = 1'b0;
    if (toggle) begin
      cnt_HIGH_MAX = 8'b00000011;
      cnt_LOW_MAX = 8'b00000011;
    end
    else begin
      cnt_HIGH_MAX = 8'b00000101;
      cnt_LOW_MAX = 8'b00000101;
    end
    // null
    case ( states)
      2'b00 :
        begin
          if (cnt < cnt_HIGH_MAX) begin
            tready_1 = 1'b1;
            // cnt<3 || cnt>7;
            if (tvalid) begin
              cnt_next = cnt + 8'b00000001;
            end
          end
          else begin
            states_next = 2'b01;
            cnt_next = 8'b00000000;
            toggle_next =  ! toggle;
          end
        end
      2'b01 :
        begin
          if (cnt < cnt_LOW_MAX) begin
            // tready = true; % cnt<3 || cnt>7;
            // if (tvalid)
            cnt_next = cnt + 8'b00000001;
            // end
          end
          else begin
            states_next = 2'b00;
            cnt_next = 8'b00000000;
            tready_1 = 1'b1;
            toggle_next =  ! toggle;
          end
        end
    endcase
  end



  assign tready = tready_1;

endmodule  // Simple_avalon_rdy_gen

