// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\avalon_st_to_axis\avalon_st_to_axis.v
// Created: 2026-04-30 11:07:21
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: avalon_st_to_axis
// Source Path: avalon_st_to_axis
// Hierarchy Level: 0
// Model version: 24.238
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module avalon_st_to_axis
          (clk,
           reset,
           av_data,
           av_valid,
           av_eop,
           m_ready,
           reset_in,
           av_ready,
           m_valid,
           m_data,
           m_last);


  input   clk;
  input   reset;
  input   [15:0] av_data;  // uint16
  input   av_valid;
  input   av_eop;
  input   m_ready;
  input   reset_in;
  output  av_ready;
  output  m_valid;
  output  [15:0] m_data;  // uint16
  output  m_last;


  reg [15:0] axi_tdata;  // uint16
  reg  axi_tvalid;
  reg  axi_tlast;
  reg  av_ready_1;
  reg [1:0] rd_ptr;  // ufix2
  reg [1:0] wr_ptr;  // ufix2
  reg [2:0] count;  // ufix3
  reg [15:0] data_buf [0:3];  // uint16 [4]
  reg  [3:0] last_buf;  // boolean [4]
  reg [1:0] rd_ptr_next;  // ufix2
  reg [1:0] wr_ptr_next;  // ufix2
  reg [2:0] count_next;  // ufix3
  reg [15:0] data_buf_next [0:3];  // uint16 [4]
  reg  [3:0] last_buf_next;  // boolean [4]
  reg  write_en;
  reg  read_en;
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_0_0;  // int32
  reg signed [31:0] t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin

        for(t_1 = 32'sd0; t_1 <= 32'sd3; t_1 = t_1 + 32'sd1) begin
          data_buf[t_1] <= 16'd0;
          last_buf[t_1] <= 1'b0;
        end

        rd_ptr <= 2'b00;
        wr_ptr <= 2'b00;
        count <= 3'b000;
      end
      else begin
        rd_ptr <= rd_ptr_next;
        wr_ptr <= wr_ptr_next;
        count <= count_next;

        for(t_0_0 = 32'sd0; t_0_0 <= 32'sd3; t_0_0 = t_0_0 + 32'sd1) begin
          data_buf[t_0_0] <= data_buf_next[t_0_0];
          last_buf[t_0_0] <= last_buf_next[t_0_0];
        end

      end
    end

  always @* begin
    rd_ptr_next = rd_ptr;
    wr_ptr_next = wr_ptr;
    count_next = count;

    for(t_0 = 32'sd0; t_0 <= 32'sd3; t_0 = t_0 + 32'sd1) begin
      data_buf_next[t_0] = data_buf[t_0];
      last_buf_next[t_0] = last_buf[t_0];
    end

    // =========================
    // READY (с запасом)
    // =========================
    // =========================
    // CONTROL
    // =========================
    write_en = av_valid && (count < 3'b100);
    read_en = (count > 3'b000) && m_ready;
    // =========================
    // OUTPUT
    // =========================
    // =========================
    // WRITE
    // =========================
    if (write_en) begin
      data_buf_next[wr_ptr] = av_data;
      last_buf_next[wr_ptr] = av_eop;
      if (wr_ptr == 2'b11) begin
        // wr_ptr = uint8(1);
        wr_ptr_next = 2'b00;
      end
      else begin
        // wr_ptr = wr_ptr + 1;
        wr_ptr_next = wr_ptr + 2'b01;
      end
    end
    // =========================
    // READ
    // =========================
    if (read_en) begin
      if (rd_ptr == 2'b11) begin
        // rd_ptr = uint8(1);
        rd_ptr_next = 2'b00;
      end
      else begin
        // rd_ptr = rd_ptr + 1;
        rd_ptr_next = rd_ptr + 2'b01;
      end
    end
    // =========================
    // COUNT
    // =========================
    if (read_en && ( ! write_en)) begin
      count_next = count - 3'b001;
    end
    else if (( ! read_en) && write_en) begin
      count_next = count + 3'b001;
    end
    //  Both or neither: cnt unchanged.
    // sel = bitconcat(fi(write_en,0,1,0,fm), fi(read_en,0,1,0,fm));
    // 
    // switch uint8(sel)
    //     case 2
    //         count = fi(count + 1, 0, count.WordLength, 0, fm);
    //     case 1
    //         count = fi(count - 1, 0, count.WordLength, 0, fm);
    //     otherwise
    // end
    axi_tdata = data_buf[rd_ptr];
    axi_tvalid = count > 3'b000;
    axi_tlast = last_buf[rd_ptr];
    av_ready_1 = count < 3'b010;
  end



  assign m_valid = axi_tvalid;

  assign m_data = axi_tdata;

  assign m_last = axi_tlast;

  assign av_ready = av_ready_1;

endmodule  // avalon_st_to_axis

