// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\avalon_st_to_axis_4word_fifo\avalon_st_to_axis_4word_fifo.v
// Created: 2026-04-30 10:56:58
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: avalon_st_to_axis_4word_fifo
// Source Path: avalon_st_to_axis_4word_fifo
// Hierarchy Level: 0
// Model version: 24.268
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module avalon_st_to_axis_4word_fifo
          (clk,
           reset,
           av_data,
           av_valid,
           av_eop,
           m_ready,
           av_sop,
           av_ready,
           m_valid,
           m_data,
           m_last);


  input   clk;
  input   reset;
  input   [15:0] av_data;  // uint16
  input   av_valid;
  input   av_eop;
  input   m_ready;
  input   av_sop;
  output  av_ready;
  output  m_valid;
  output  [15:0] m_data;  // uint16
  output  m_last;


  reg [15:0] axi_tdata;  // uint16
  reg  axi_tvalid;
  reg  axi_tlast;
  reg  av_ready_1;
  reg [15:0] fifo_data [0:3];  // uint16 [4]
  reg  [3:0] fifo_last;  // boolean [4]
  reg [1:0] wr_ptr;  // ufix2
  reg [1:0] rd_ptr;  // ufix2
  reg [2:0] cnt;  // ufix3
  reg [15:0] out_data;  // uint16
  reg  out_last;
  reg  out_valid;
  reg [15:0] fifo_data_next [0:3];  // uint16 [4]
  reg  [3:0] fifo_last_next;  // boolean [4]
  reg [1:0] wr_ptr_next;  // ufix2
  reg [1:0] rd_ptr_next;  // ufix2
  reg [2:0] cnt_next;  // ufix3
  reg [15:0] out_data_next;  // uint16
  reg  out_last_next;
  reg  out_valid_next;
  reg [15:0] fifo_head_d;  // uint16
  reg  fifo_head_l;
  reg  out_consumed;
  reg  out_free;
  reg  do_rd;
  reg  do_bypass;
  reg  do_wr;
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_0_0;  // int32
  reg signed [31:0] t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin

        for(t_1 = 32'sd0; t_1 <= 32'sd3; t_1 = t_1 + 32'sd1) begin
          fifo_data[t_1] <= 16'd0;
          fifo_last[t_1] <= 1'b0;
        end

        wr_ptr <= 2'b00;
        rd_ptr <= 2'b00;
        cnt <= 3'b000;
        out_data <= 16'd0;
        out_last <= 1'b0;
        out_valid <= 1'b0;
      end
      else begin

        for(t_0_0 = 32'sd0; t_0_0 <= 32'sd3; t_0_0 = t_0_0 + 32'sd1) begin
          fifo_data[t_0_0] <= fifo_data_next[t_0_0];
          fifo_last[t_0_0] <= fifo_last_next[t_0_0];
        end

        wr_ptr <= wr_ptr_next;
        rd_ptr <= rd_ptr_next;
        cnt <= cnt_next;
        out_data <= out_data_next;
        out_last <= out_last_next;
        out_valid <= out_valid_next;
      end
    end

  always @* begin

    for(t_0 = 32'sd0; t_0 <= 32'sd3; t_0 = t_0 + 32'sd1) begin
      fifo_data_next[t_0] = fifo_data[t_0];
      fifo_last_next[t_0] = fifo_last[t_0];
    end

    wr_ptr_next = wr_ptr;
    rd_ptr_next = rd_ptr;
    cnt_next = cnt;
    out_data_next = out_data;
    out_last_next = out_last;
    out_valid_next = out_valid;
    //AVALON_TO_AXIS  Avalon-ST → AXI4-Stream bridge (registered)
    //                    ┌──────────────────────────────────────────────┐
    //                    │            avalon_to_axis                    │
    //                    │                                              │
    // av_data ──────────►│──┬─── do_bypass ────────┐                    │
    // av_valid ─────────►│  │   (cnt==0 &          │                    │
    // av_endofpacket ───►│  │    out_free)         │                    │
    // av_startofpacket ─►│  │                      ▼                    │
    //                    │  │  ┌────────────┐   ┌──────────┐            │
    //                    │  └─►│ FIFO 4×Dw  │──►│ out_reg  │──►axi_tdata
    //                    │     │            │   │          │──►axi_tvalid
    //                    │     │ cnt>=2:    │   │          │──►axi_tlast
    //                    │     │ av_ready=0 │   └────┬─────┘            │
    //                    │     │            │        │                  │
    //                    │     │ cnt>=4:    │   axi_tready              │
    //                    │     │ stop write │◄───────┘                  │
    //                    │     └────────────┘                           │
    //                    │                                              │
    //                    │  av_ready = (cnt < 2) ─────────────►av_ready │
    //                    └──────────────────────────────────────────────┘
    //   Fully registered data path — no combinatorial feedthrough from
    //   av_data to axi_tdata or from axi_tready to av_ready.
    //
    //   Architecture:
    //       Avalon-ST → [4-word circular FIFO] → [output register] → AXI4-Stream
    //
    //   Back-pressure:
    //       av_ready deasserts when FIFO occupancy reaches AFULL_THRESH (2).
    //       Physical FIFO depth is 4, so 2 free slots remain after deassertion.
    //       An upstream source with up to 2 cycles of ready-latency can still
    //       push words that will be accepted (the module keeps writing to the
    //       FIFO as long as physical space exists, regardless of av_ready).
    //
    //   Bypass path:
    //       When the FIFO is empty and the output register is free, input data
    //       loads directly into the output register (still registered — appears
    //       on axi_tdata one clock cycle later).  This avoids a 2-cycle bubble
    //       on an empty pipeline.
    //
    // ======================= user parameter ==================================
    // DATA_WIDTH = 16;            % av_data / axi_tdata width in bits
    // ======================= design constants ================================
    // physical depth  (must be power-of-two >= 4)
    // FIFO_MASK    = FIFO_DEPTH-1;    % FIFO_DEPTH - 1, for pointer wrap via bitand
    // av_ready off when cnt >= this
    //   FIFO_DEPTH - AFULL_THRESH == 2 → 2-word acceptance margin
    // ZERO_DATA = fi(0, 0, DATA_WIDTH, 0);
    // ======================= persistent state (flip-flops) ===================
    // FIFO storage arrays
    // FIFO pointers & occupancy
    // output register
    // ======================= drive outputs (purely from registers) ===========
    //  av_ready depends only on the cnt register — no combinatorial path
    //  from axi_tready.
    // ======================= combinatorial next-state logic ==================
    // -- AXI-side handshake ---------------------------------------------------
    out_consumed = out_valid && m_ready;
    // output word accepted by slave
    out_free = ( ! out_valid) || out_consumed;
    // output register available
    // -- FIFO head read (value gated by do_rd) --------------------------------
    // rd_one       = rd_ptr + uint8(1);           % 1-based MATLAB index
    fifo_head_d = fifo_data[rd_ptr];
    fifo_head_l = fifo_last[rd_ptr];
    // -- Control signals ------------------------------------------------------
    //  do_rd     : move FIFO head → output register
    //  do_bypass : route input → output register directly (FIFO empty shortcut)
    //  do_wr     : write input into FIFO
    //
    //  do_rd and do_bypass are mutually exclusive (cnt>0 vs cnt==0).
    do_rd = out_free && ({5'b0, cnt} > 8'b00000000);
    do_bypass = (av_valid && out_free) && (cnt == 3'b000);
    do_wr = (av_valid && ( ! do_bypass)) && (cnt < 3'b100);
    //  Accepts input even when av_ready==0 — this is the 2-word tolerance:
    //  the source may still be pushing after it "sees" the deassertion.
    // ======================= update output register ==========================
    if (do_rd) begin
      out_data_next = fifo_head_d;
      out_last_next = fifo_head_l;
      out_valid_next = 1'b1;
    end
    else if (do_bypass) begin
      out_data_next = av_data;
      out_last_next = av_eop;
      out_valid_next = 1'b1;
    end
    else if (out_consumed) begin
      out_valid_next = 1'b0;
      // out_data  = ZERO_DATA;  % keep bus clean (optional)
      out_last_next = 1'b0;
    end
    //  Implicit else: registers hold their values.
    // ======================= update FIFO storage =============================
    if (do_wr) begin
      fifo_data_next[wr_ptr] = av_data;
      fifo_last_next[wr_ptr] = av_eop;
      // wr_ptr = bitand(wr_ptr + uint8(1), FIFO_MASK);
      if (wr_ptr == 2'b11) begin
        wr_ptr_next = 2'b00;
      end
      else begin
        wr_ptr_next = wr_ptr + 2'b01;
      end
    end
    if (do_rd) begin
      // rd_ptr = bitand(rd_ptr + uint8(1), FIFO_MASK);
      if (rd_ptr == 2'b11) begin
        rd_ptr_next = 2'b00;
      end
      else begin
        rd_ptr_next = rd_ptr + 2'b01;
      end
    end
    // ======================= update count ====================================
    if (do_rd && ( ! do_wr)) begin
      cnt_next = cnt - 3'b001;
    end
    else if (( ! do_rd) && do_wr) begin
      cnt_next = cnt + 3'b001;
    end
    //  Both or neither: cnt unchanged.
    axi_tdata = out_data;
    axi_tvalid = out_valid;
    axi_tlast = out_last;
    av_ready_1 = cnt < 3'b010;
  end



  assign m_valid = axi_tvalid;

  assign m_data = axi_tdata;

  assign m_last = axi_tlast;

  assign av_ready = av_ready_1;

endmodule  // avalon_st_to_axis_4word_fifo

