// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\simple_avalon_st_generator\simple_avalon_st_generator.v
// Created: 2026-04-30 10:57:16
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simple_avalon_st_generator
// Source Path: simple_avalon_st_generator
// Hierarchy Level: 0
// Model version: 24.262
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simple_avalon_st_generator
          (clk,
           reset,
           av_ready,
           N,
           av_valid,
           av_data,
           av_sop,
           av_eop);


  input   clk;
  input   reset;
  input   av_ready;
  input   [7:0] N;  // uint8
  output  av_valid;
  output  [15:0] av_data;  // uint16
  output  av_sop;
  output  av_eop;


  reg  Delay4_out1;
  reg [15:0] av_data_1;  // uint16
  reg  av_valid_1;
  reg  av_sop_1;
  reg  av_eop_1;
  reg [15:0] cnt;  // ufix16
  reg [15:0] beat_cnt;  // ufix16
  reg  first_beat;
  reg [15:0] cnt_next;  // ufix16
  reg [15:0] beat_cnt_next;  // ufix16
  reg  first_beat_next;
  reg  Delay1_out1;
  reg [15:0] Delay_out1;  // uint16
  reg  Delay2_out1;
  reg  Delay3_out1;


  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        Delay4_out1 <= av_ready;
      end
    end



  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        cnt <= 16'b0000000000000000;
        beat_cnt <= 16'b0000000000000000;
        first_beat <= 1'b1;
      end
      else begin
        cnt <= cnt_next;
        beat_cnt <= beat_cnt_next;
        first_beat <= first_beat_next;
      end
    end

  always @(Delay4_out1, N, beat_cnt, cnt, first_beat) begin
    cnt_next = cnt;
    beat_cnt_next = beat_cnt;
    first_beat_next = first_beat;
    av_valid_1 = 1'b0;
    av_sop_1 = 1'b0;
    av_eop_1 = 1'b0;
    // switch states
    // case 0
    if (Delay4_out1) begin
      av_sop_1 = first_beat;
      av_valid_1 = 1'b1;
      if (beat_cnt == {8'b0, N}) begin
        av_eop_1 = 1'b1;
        first_beat_next = 1'b1;
        beat_cnt_next = 16'b0000000000000000;
      end
      else begin
        first_beat_next = 1'b0;
        beat_cnt_next = beat_cnt + 16'b0000000000000001;
      end
      cnt_next = cnt + 16'b0000000000000001;
    end
    av_data_1 = cnt;
  end



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        Delay1_out1 <= av_valid_1;
      end
    end



  assign av_valid = Delay1_out1;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 16'b0000000000000000;
      end
      else begin
        Delay_out1 <= av_data_1;
      end
    end



  assign av_data = Delay_out1;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        Delay2_out1 <= av_sop_1;
      end
    end



  assign av_sop = Delay2_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        Delay3_out1 <= av_eop_1;
      end
    end



  assign av_eop = Delay3_out1;

endmodule  // simple_avalon_st_generator

