// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\simple_avalonst_axis_checker\simple_avalonst_axis_checker.v
// Created: 2026-04-30 12:01:21
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: simple_avalonst_axis_checker
// Source Path: simple_avalonst_axis_checker
// Hierarchy Level: 0
// Model version: 16.278
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module simple_avalonst_axis_checker
          (clk,
           reset,
           axis_tready,
           axis_tdata,
           axis_tvalid,
           axis_tlast,
           N,
           av_data,
           av_valid,
           av_eop,
           av_sop,
           axi_err_out,
           av_err_out);


  input   clk;
  input   reset;
  input   axis_tready;
  input   [15:0] axis_tdata;  // uint16
  input   axis_tvalid;
  input   axis_tlast;
  input   [7:0] N;  // uint8
  input   [15:0] av_data;  // uint16
  input   av_valid;
  input   av_eop;
  input   av_sop;
  output  axi_err_out;
  output  av_err_out;


  reg  axi_err_out_1;
  reg  av_err_out_1;
  reg [15:0] axi_cnt;  // ufix16
  reg [15:0] axi_beat_cnt;  // ufix16
  reg [15:0] av_cnt;  // ufix16
  reg [15:0] av_beat_cnt;  // ufix16
  reg  av_first_beat;
  reg [15:0] axi_cnt_next;  // ufix16
  reg [15:0] axi_beat_cnt_next;  // ufix16
  reg [15:0] av_cnt_next;  // ufix16
  reg [15:0] av_beat_cnt_next;  // ufix16
  reg  av_first_beat_next;


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        axi_cnt <= 16'b0000000000000000;
        axi_beat_cnt <= 16'b0000000000000000;
        av_cnt <= 16'b0000000000000000;
        av_beat_cnt <= 16'b0000000000000000;
        av_first_beat <= 1'b1;
      end
      else begin
        axi_cnt <= axi_cnt_next;
        axi_beat_cnt <= axi_beat_cnt_next;
        av_cnt <= av_cnt_next;
        av_beat_cnt <= av_beat_cnt_next;
        av_first_beat <= av_first_beat_next;
      end
    end

  always @(N, av_beat_cnt, av_cnt, av_data, av_eop, av_first_beat, av_sop, av_valid,
       axi_beat_cnt, axi_cnt, axis_tdata, axis_tlast, axis_tready, axis_tvalid) begin
    axi_cnt_next = axi_cnt;
    axi_beat_cnt_next = axi_beat_cnt;
    av_cnt_next = av_cnt;
    av_beat_cnt_next = av_beat_cnt;
    av_first_beat_next = av_first_beat;
    axi_err_out_1 = 1'b0;
    if (axis_tready && axis_tvalid) begin
      axi_err_out_1 = (axis_tdata != axi_cnt) || (axis_tlast && (axi_beat_cnt != {8'b0, N}));
      if (axis_tlast) begin
        axi_beat_cnt_next = 16'b0000000000000000;
      end
      else begin
        axi_beat_cnt_next = axi_beat_cnt + 16'b0000000000000001;
      end
      axi_cnt_next = axi_cnt + 16'b0000000000000001;
      // else
      // axi_err_out = false;
    end
    av_err_out_1 = 1'b0;
    if (av_valid) begin
      av_err_out_1 = (((av_sop != av_first_beat) || (av_data != av_cnt)) || (av_sop && av_eop)) || (av_eop && (av_beat_cnt != {8'b0, N}));
      // if (av_beat_cnt==N)
      if (av_eop) begin
        av_first_beat_next = 1'b1;
        av_beat_cnt_next = 16'b0000000000000000;
      end
      else begin
        av_first_beat_next = 1'b0;
        av_beat_cnt_next = av_beat_cnt + 16'b0000000000000001;
      end
      av_cnt_next = av_cnt + 16'b0000000000000001;
    end
  end



  assign axi_err_out = axi_err_out_1;

  assign av_err_out = av_err_out_1;

endmodule  // simple_avalonst_axis_checker

