// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\axis_to_avalon_st_skid2\axis_to_avalon_st_skid2.v
// Created: 2026-04-30 12:30:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: axis_to_avalon_st_skid2
// Source Path: axis_to_avalon_st_skid2
// Hierarchy Level: 0
// Model version: 24.257
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module axis_to_avalon_st_skid2
          (clk,
           reset,
           axi_data,
           axi_valid,
           axi_last,
           av_ready,
           av_valid,
           av_data,
           av_sop,
           av_eop,
           axi_tready);


  input   clk;
  input   reset;
  input   [15:0] axi_data;  // uint16
  input   axi_valid;
  input   axi_last;
  input   av_ready;
  output  av_valid;
  output  [15:0] av_data;  // uint16
  output  av_sop;
  output  av_eop;
  output  axi_tready;


  reg [15:0] av_data_1;  // uint16
  reg  av_valid_1;
  reg  av_startofpacket;
  reg  av_endofpacket;
  reg  axi_tready_1;
  reg [15:0] data0;  // uint16
  reg  valid0;
  reg  last0;
  reg [15:0] data1;  // uint16
  reg  valid1;
  reg  last1;
  reg  in_packet;
  reg [15:0] data0_next;  // uint16
  reg  valid0_next;
  reg  last0_next;
  reg [15:0] data1_next;  // uint16
  reg  valid1_next;
  reg  last1_next;
  reg  in_packet_next;
  reg  axi_tready1;
  reg  next_valid0;


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        data0 <= 16'd0;
        valid0 <= 1'b0;
        last0 <= 1'b0;
        data1 <= 16'd0;
        valid1 <= 1'b0;
        last1 <= 1'b0;
        in_packet <= 1'b0;
      end
      else begin
        data0 <= data0_next;
        valid0 <= valid0_next;
        last0 <= last0_next;
        data1 <= data1_next;
        valid1 <= valid1_next;
        last1 <= last1_next;
        in_packet <= in_packet_next;
      end
    end

  always @(av_ready, axi_data, axi_last, axi_valid, data0, data1, in_packet, last0, last1,
       valid0, valid1) begin
    in_packet_next = in_packet;
    // =========================
    // OUTPUT LOGIC (stage0)
    // =========================
    av_valid_1 = valid0 && av_ready;
    // valid0;
    av_startofpacket = (valid0 && ( ! in_packet)) && av_ready;
    // valid0 && ~in_packet;
    av_endofpacket = (valid0 && last0) && av_ready;
    // valid0 && last0;
    // =========================
    // AXI READY
    // =========================
    // можем принимать, если есть место хотя бы в одном регистре
    axi_tready1 =  ! valid1;
    // =========================
    // NEXT STATE (локальные копии)
    // =========================
    data0_next = data0;
    next_valid0 = valid0;
    last0_next = last0;
    data1_next = data1;
    valid1_next = valid1;
    last1_next = last1;
    // next_in_packet = in_packet;
    // =========================
    // 1. Выдача в Avalon
    // =========================
    if (valid0 && av_ready) begin
      next_valid0 = 1'b0;
      in_packet_next =  ! last0;
    end
    // =========================
    // 2. Перемещение stage1 -> stage0
    // =========================
    if (( ! next_valid0) && valid1) begin
      data0_next = data1;
      next_valid0 = 1'b1;
      last0_next = last1;
      valid1_next = 1'b0;
    end
    // =========================
    // 3. Прием AXI
    // =========================
    if (axi_tready1 && axi_valid) begin
      if ( ! next_valid0) begin
        // сразу в stage0
        data0_next = axi_data;
        next_valid0 = 1'b1;
        last0_next = axi_last;
      end
      else begin
        // в skid (stage1)
        data1_next = axi_data;
        valid1_next = 1'b1;
        last1_next = axi_last;
      end
    end
    // =========================
    // COMMIT
    // =========================
    valid0_next = next_valid0;
    // in_packet = next_in_packet;
    av_data_1 = data0;
    axi_tready_1 = axi_tready1;
  end



  assign av_sop = av_startofpacket;

  assign av_eop = av_endofpacket;

  assign av_valid = av_valid_1;

  assign av_data = av_data_1;

  assign axi_tready = axi_tready_1;

endmodule  // axis_to_avalon_st_skid2

