// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\axis_to_avalon_st_skid\axis_to_avalon_st_skid.v
// Created: 2026-04-30 12:30:36
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: axis_to_avalon_st_skid
// Source Path: axis_to_avalon_st_skid
// Hierarchy Level: 0
// Model version: 24.253
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module axis_to_avalon_st_skid
          (clk,
           reset,
           axi_data,
           axi_valid,
           axi_last,
           av_ready,
           av_valid,
           av_data,
           av_sop,
           av_eop,
           axi_tready);


  input   clk;
  input   reset;
  input   [15:0] axi_data;  // uint16
  input   axi_valid;
  input   axi_last;
  input   av_ready;
  output  av_valid;
  output  [15:0] av_data;  // uint16
  output  av_sop;
  output  av_eop;
  output  axi_tready;


  reg [15:0] av_data_1;  // uint16
  reg  av_valid_1;
  reg  av_startofpacket;
  reg  av_endofpacket;
  reg  axi_tready_1;
  reg [15:0] out_data;  // uint16
  reg  out_valid;
  reg  out_sop;
  reg  out_eop;
  reg [15:0] skid_data;  // uint16
  reg  skid_valid;
  reg  skid_sop;
  reg  skid_eop;
  reg  first_word;
  reg [15:0] out_data_next;  // uint16
  reg  out_valid_next;
  reg  out_sop_next;
  reg  out_eop_next;
  reg [15:0] skid_data_next;  // uint16
  reg  skid_valid_next;
  reg  skid_sop_next;
  reg  skid_eop_next;
  reg  first_word_next;
  reg  input_accepted;
  reg  out_consumed;


  always @(posedge clk or posedge reset)
    begin : fsm_eml_process
      if (reset == 1'b1) begin
        out_data <= 16'd0;
        out_valid <= 1'b0;
        out_sop <= 1'b0;
        out_eop <= 1'b0;
        skid_data <= 16'd0;
        skid_valid <= 1'b0;
        skid_sop <= 1'b0;
        skid_eop <= 1'b0;
        first_word <= 1'b1;
      end
      else begin
        out_data <= out_data_next;
        out_valid <= out_valid_next;
        out_sop <= out_sop_next;
        out_eop <= out_eop_next;
        skid_data <= skid_data_next;
        skid_valid <= skid_valid_next;
        skid_sop <= skid_sop_next;
        skid_eop <= skid_eop_next;
        first_word <= first_word_next;
      end
    end

  always @(av_ready, axi_data, axi_last, axi_valid, first_word, out_data, out_eop,
       out_sop, out_valid, skid_data, skid_eop, skid_sop, skid_valid) begin
    out_data_next = out_data;
    out_valid_next = out_valid;
    out_sop_next = out_sop;
    out_eop_next = out_eop;
    skid_data_next = skid_data;
    skid_valid_next = skid_valid;
    skid_sop_next = skid_sop;
    skid_eop_next = skid_eop;
    first_word_next = first_word;
    //AXIS_TO_AVALON  AXI4-Stream → Avalon-ST bridge (registered, skid buffer)
    //                         ┌─────────────────────────────────┐
    //                         │         axis_to_avalon          │
    //                         │                                 │
    // axi_tdata ──┐   ┌───────┤──► [skid_buf] ──► [out_reg] ──► ├──► av_data
    // axi_tvalid ─┤   │ MUX   │        │              │         ├──► av_valid
    // axi_tlast ──┤   │       │        │              │         ├──► av_startofpacket
    //             │   │       │   skid_valid      out_valid     ├──► av_endofpacket
    //             │   │       │        │                        │
    //             │   │       │    ┌───┴───┐                    │
    //             │   │       │    │  NOT  ├───────────────────►├──► axi_tready
    //             │   │       │    └───────┘                    │
    // av_ready ───┼───┘       │                                 │
    //             │           │   [first_word] — трекинг SOP    │
    //             │           └─────────────────────────────────┘
    //             │
    //             ▼
    //        Нет комбинаторных путей input → output
    //        Латентность: 1 такт
    //        Ресурсы:     2 × DATA_WIDTH + 9 FF
    //
    //   Все выходы полностью регистровые: нет комбинаторных путей
    //   от входных портов к выходным портам. Для поддержки backpressure
    //   без потери данных используется skid-буфер глубиной 1.
    //
    //   Латентность:  1 такт (в установившемся режиме).
    //   Пропускная способность: 1 слово/такт (при отсутствии backpressure).
    //   Ресурсы:      2 × DATA_WIDTH + 9 flip-flop.
    // ============================================================
    //  Регистры
    //  ============================================================
    // --- Выходной регистр (output stage) ---
    // --- Skid-буфер (промежуточный регистр) ---
    // --- Отслеживание границ пакетов ---
    //     true = следующее принятое слово является первым в пакете
    // ============================================================
    //  Выходы — напрямую из регистров, без комбинаторной логики
    //  от входных портов
    //  ============================================================
    av_valid_1 = out_valid && av_ready;
    // out_valid;
    av_startofpacket = out_sop && av_ready;
    // out_sop;
    av_endofpacket = out_eop && av_ready;
    // out_eop;
    // зависит ТОЛЬКО от регистра
    // ============================================================
    //  Детекция хэндшейков (комбинаторно, но НЕ на выходных портах)
    //  ============================================================
    //  Входной хэндшейк: AXI-источник передаёт слово
    input_accepted = axi_valid && ( ! skid_valid);
    //  Выходной хэндшейк: Avalon-приёмник забирает слово
    out_consumed = out_valid && av_ready;
    // ============================================================
    //  Метаданные принимаемого слова
    //  (вычисляются на основе текущего first_word и входов)
    //  ============================================================
    // SOP = первое слово пакета
    // EOP = tlast от AXI-источника
    // ============================================================
    //  Автомат обновления состояния
    //  ============================================================
    //
    //  Инвариант: если skid_valid = true, то out_valid = true
    //  (данные попадают в skid только когда выход занят и не потреблён)
    //
    //  Три основных сценария:
    //
    //  A) skid занят  → новый вход невозможен (tready = 0)
    //       A1) выход потреблён   → skid → output, skid освобождается
    //       A2) выход не потреблён → всё сохраняется (stall)
    //
    //  B) skid пуст   → новый вход возможен (tready = 1)
    //       B1) вход принят, выход свободен  → вход → output напрямую
    //       B2) вход принят, выход занят     → вход → skid
    //       B3) входа нет, выход потреблён   → output освобождается
    //       B4) входа нет, выход не потреблён → всё сохраняется
    if (skid_valid) begin
      // ---- Сценарий A: skid-буфер занят, вход заблокирован ----
      if (out_consumed) begin
        // A1: Avalon-приёмник забрал данные — сливаем skid в output
        out_data_next = skid_data;
        out_valid_next = 1'b1;
        out_sop_next = skid_sop;
        out_eop_next = skid_eop;
        skid_valid_next = 1'b0;
      end
      // A2: Avalon-приёмник не готов — удерживаем всё без изменений
    end
    else begin
      // ---- Сценарий B: skid-буфер пуст, вход доступен ----
      if (input_accepted) begin
        if (out_consumed || ( ! out_valid)) begin
          // B1: Выходной слот свободен — вход идёт сразу в output
          out_data_next = axi_data;
          out_valid_next = 1'b1;
          out_sop_next = first_word;
          out_eop_next = axi_last;
        end
        else begin
          // B2: Выход занят (stall) — вход буферизуется в skid
          skid_data_next = axi_data;
          skid_valid_next = 1'b1;
          skid_sop_next = first_word;
          skid_eop_next = axi_last;
        end
        // Обновление трекинга границ пакетов
        if (axi_last) begin
          first_word_next = 1'b1;
          // конец пакета — следующий = SOP
        end
        else begin
          first_word_next = 1'b0;
          // середина пакета
        end
      end
      else begin
        // B3/B4: Входных данных нет
        if (out_consumed) begin
          // B3: Выходные данные забраны, новых нет
          out_valid_next = 1'b0;
        end
        // B4: Ничего не происходит — удерживаем состояние
      end
    end
    av_data_1 = out_data;
    axi_tready_1 =  ! skid_valid;
  end



  assign av_sop = av_startofpacket;

  assign av_eop = av_endofpacket;

  assign av_valid = av_valid_1;

  assign av_data = av_data_1;

  assign axi_tready = axi_tready_1;

endmodule  // axis_to_avalon_st_skid

