// -------------------------------------------------------------
// 
// File Name: C:\MATLAB_R2012b_work\work\SATA3X_SOYUZ25\hdlsrc\AXIS_rnd_master_32bit\AXIS_rnd_master_32bit.v
// Created: 2026-09-09 17:08:54
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: AXIS_rnd_master_32bit
// Source Path: AXIS_rnd_master_32bit
// Hierarchy Level: 0
// Model version: 16.843
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AXIS_rnd_master_32bit
          (clk,
           reset,
           lane_up,
           channel_up,
           m_axis_tready,
           enable,
           m_axis_tdata,
           m_axis_tvalid,
           m_axis_tlast,
           m_axis_tkeep,
           some_length_out,
           m_axis_tdata1);


  input   clk;
  input   reset;
  input   lane_up;
  input   channel_up;
  input   m_axis_tready;
  input   enable;
  output  [31:0] m_axis_tdata;  // uint32
  output  m_axis_tvalid;
  output  m_axis_tlast;
  output  [3:0] m_axis_tkeep;  // ufix4
  output  [10:0] some_length_out;  // ufix11
  output  [31:0] m_axis_tdata1;  // uint32


  wire [15:0] rnd;  // uint16
  reg [31:0] state;  // uint32
  wire [31:0] state_next;  // uint32
  wire [31:0] rot;  // uint32
  wire [31:0] x;  // uint32
  wire [31:0] x_1;  // uint32
  wire [31:0] x_2;  // uint32
  wire [31:0] rot_1;  // uint32
  reg  corrupt_data_out;
  reg [31:0] m_axis_tdata_1;  // uint32
  reg  m_axis_tvalid_1;
  reg  m_axis_tlast_1;
  reg [3:0] m_axis_tkeep_1;  // ufix4
  reg [10:0] some_length_out_1;  // ufix11
  reg [1:0] state_reg;  // ufix2
  reg [10:0] counter;  // ufix11
  reg [10:0] some_length;  // ufix11
  reg [31:0] AXIS_counter;  // ufix32
  reg [31:0] p_data;  // ufix32
  reg  p_last;
  reg  p_valid;
  reg [3:0] p_keep;  // ufix4
  reg [31:0] s_data;  // ufix32
  reg  s_last;
  reg  s_valid;
  reg [3:0] s_keep;  // ufix4
  reg  corrupt_data_reg;
  reg  corrupt_data_reg_d;
  reg [1:0] state_reg_next;  // ufix2
  reg [10:0] counter_next;  // ufix11
  reg [10:0] some_length_next;  // ufix11
  reg [31:0] AXIS_counter_next;  // ufix32
  reg [31:0] p_data_next;  // ufix32
  reg  p_last_next;
  reg  p_valid_next;
  reg [3:0] p_keep_next;  // ufix4
  reg [31:0] s_data_next;  // ufix32
  reg  s_last_next;
  reg  s_valid_next;
  reg [3:0] s_keep_next;  // ufix4
  reg  corrupt_data_reg_next;
  reg  corrupt_data_reg_d_next;
  wire [31:0] Multiport_Switch_out1;  // uint32
  reg  in_ready;
  reg  push;
  reg [31:0] push_data;  // ufix32
  reg  push_last;
  reg [3:0] some_length_cut;  // ufix4
  reg [3:0] counter_cut;  // ufix4
  reg [3:0] last_m_axis_count;  // ufix4
  reg  t_0;
  reg  accept;
  reg  t_1;
  reg [3:0] c_r;  // ufix4
  reg [10:0] a;  // ufix11
  reg [10:0] c;  // ufix11
  reg [10:0] c_0;  // ufix11
  reg [4:0] c_1;  // ufix5
  reg [10:0] a_0;  // ufix11
  reg  p_valid_temp;
  reg  s_valid_temp;
  reg [2:0] t_2;  // ufix3
  reg [7:0] t_3;  // uint8


  always @(posedge clk or posedge reset)
    begin : random11_process
      if (reset == 1'b1) begin
        state <= 32'd2779115811;
      end
      else begin
        state <= state_next;
      end
    end

  // x = state_in;
  assign x = state ^ (state <<< 8'd13);
  assign x_1 = x ^ (x >> 32'sd17);
  assign x_2 = x_1 ^ (x_1 <<< 8'd5);
  assign state_next = x_2;
  // rotate right на 7
  assign rot = (x_2 >> 32'sd7) | (x_2 <<< 8'd25);
  // rot_out_0 = rot;
  // x_out = x;
  assign rot_1 = rot >> 32'sd21;
  assign rnd = rot_1[15:0];



  always @(posedge clk or posedge reset)
    begin : AXIS_rnd_master_32bit_1_process
      if (reset == 1'b1) begin
        state_reg <= 2'b00;
        AXIS_counter <= 32'b00000000000000000000000000000000;
        some_length <= 11'b00001000000;
        counter <= 11'b00000000000;
        p_data <= 32'b00000000000000000000000000000000;
        p_last <= 1'b0;
        p_valid <= 1'b0;
        p_keep <= 4'b1111;
        s_data <= 32'b00000000000000000000000000000000;
        s_last <= 1'b0;
        s_valid <= 1'b0;
        s_keep <= 4'b1111;
        corrupt_data_reg <= 1'b0;
        corrupt_data_reg_d <= 1'b0;
      end
      else begin
        state_reg <= state_reg_next;
        counter <= counter_next;
        some_length <= some_length_next;
        AXIS_counter <= AXIS_counter_next;
        p_data <= p_data_next;
        p_last <= p_last_next;
        p_valid <= p_valid_next;
        p_keep <= p_keep_next;
        s_data <= s_data_next;
        s_last <= s_last_next;
        s_valid <= s_valid_next;
        s_keep <= s_keep_next;
        corrupt_data_reg <= corrupt_data_reg_next;
        corrupt_data_reg_d <= corrupt_data_reg_d_next;
      end
    end

  always @(AXIS_counter, channel_up, corrupt_data_reg, corrupt_data_reg_d, counter,
       enable, lane_up, m_axis_tready, p_data, p_keep, p_last, p_valid, rnd,
       s_data, s_keep, s_last, s_valid, some_length, state_reg) begin
    c = 11'b00000000000;
    c_0 = 11'b00000000000;
    c_1 = 5'b00000;
    t_2 = 3'b000;
    a = 11'b00000000000;
    t_3 = 8'd0;
    a_0 = 11'b00000000000;
    p_valid_temp = p_valid;
    s_valid_temp = s_valid;
    counter_next = counter;
    some_length_next = some_length;
    AXIS_counter_next = AXIS_counter;
    p_data_next = p_data;
    p_last_next = p_last;
    p_keep_next = p_keep;
    s_data_next = s_data;
    s_last_next = s_last;
    s_keep_next = s_keep;
    corrupt_data_reg_next = corrupt_data_reg;
    // ----------------- AXIS transmit ---------------
    // FSM + Skid-buffer. Между D_FIFO/D_WORD и AXIS — две регистровые ступени. с формированием TLAST каждые (N+1) beat'ов.
    // ---------------- Параметр пакета ----------------
    // N = fi(N_in,0,8,0,fm);   % количество слов из D_FIFO до вставки D_WORD с TLAST
    // N = 5;
    // ---------------- Регистры FSM ------------------
    // ---------------- Primary stage (видна на AXIS) --
    // ---------------- Skid stage (резерв) -----------
    // ---------------- Выходы ------------------------
    corrupt_data_out = corrupt_data_reg && ( ! corrupt_data_reg_d);
    corrupt_data_reg_d_next = corrupt_data_reg;
    // ---------------- Skid-контракт -----------------
    // Можно принять ещё одно слово, пока обе ступени не заняты.
    t_0 = p_valid && s_valid;
    in_ready =  ! t_0;
    // Факт передачи beat'а получателем (только по primary).
    accept = p_valid && m_axis_tready;
    // ---------------- Локальные «push» из FSM -------
    push = 1'b0;
    // push_data = fi(0, AXIS_nt, fm);
    push_data = AXIS_counter;
    c_r = 4'b1111;
    push_last = 1'b0;
    // ---------------- FSM ---------------
    // switch (bitsliceget(D_FIFO_rd_data,AXIS_nt.WordLength+2,AXIS_nt.WordLength+1))
    //     case 0
    //         rd_keep = fi(bin2dec('0001'),0,p_keep.WordLength,0,fm);
    //     case 1
    //         rd_keep = fi(bin2dec('0011'),0,p_keep.WordLength,0,fm);
    //     case 2
    //         rd_keep = fi(bin2dec('0111'),0,p_keep.WordLength,0,fm);
    //     case 3
    //         rd_keep = fi(bin2dec('1111'),0,p_keep.WordLength,0,fm);
    //     otherwise
    //         rd_keep = fi(0,0,4,0,fm);
    // end
    some_length_cut = some_length[3:0];
    counter_cut = counter[3:0];
    last_m_axis_count = some_length_cut - counter_cut;
    t_1 = channel_up && lane_up;
    if ( ! t_1) begin
      state_reg_next = 2'b00;
      counter_next = 11'b00000000000;
      some_length_next = 11'b00000111100;
      AXIS_counter_next = 32'b00000000000000000000000000000000;
      p_valid_temp = 1'b0;
      s_valid_temp = 1'b0;
    end
    else begin
      case ( state_reg)
        2'b00 :
          begin
            if (enable) begin
              if (rnd < 16'd60) begin
                some_length_next = 11'b00000111100;
              end
              else if (rnd > 16'd1514) begin
                // some_length = fi(LENGTH_MAX_LIMIT, 0, some_length.WordLength, 0, fm);
                a = rnd[10:0];
                c = a >> 8'd1;
                some_length_next = c;
              end
              else begin
                some_length_next = rnd[10:0];
              end
              state_reg_next = 2'b01;
              counter_next = 11'b00000000000;
            end
            else begin
              state_reg_next = 2'b00;
            end
          end
        2'b01 :
          begin
            // STREAM:
            // if (in_ready)
            if (in_ready && enable) begin
              push = 1'b1;
              // push_data    = fi(AXIS_counter, AXIS_nt, fm);
              // AXIS_counter = fi(AXIS_counter + 1,0,AXIS_counter.WordLength,0,fm);
              push_data = {counter[7:0] + 8'b00000011, counter[7:0] + 8'b00000010, counter[7:0] + 8'b00000001, counter[7:0]};
              counter_next = counter + 11'b00000000100;
              state_reg_next = 2'b10;
            end
            else begin
              state_reg_next = 2'b01;
            end
          end
        default :
          begin
            if (in_ready) begin
              push = 1'b1;
              // push_data    = fi(AXIS_counter, AXIS_nt, fm);
              push_data = {counter[7:0] + 8'b00000011, counter[7:0] + 8'b00000010, counter[7:0] + 8'b00000001, counter[7:0]};
              // AXIS_counter = fi(AXIS_counter + 1,0,AXIS_counter.WordLength,0,fm);
              c_0 = some_length >> 8'd1;
              corrupt_data_reg_next = counter >= c_0;
              // if (counter+4 < some_length)
              if (((({1'b0, counter}) + 12'b000000000100) < {1'b0, some_length}) && enable) begin
                counter_next = counter + 11'b00000000100;
                state_reg_next = 2'b10;
              end
              else begin
                push_last = 1'b1;
                t_2 = last_m_axis_count[2:0];
                t_3 = {5'b0, t_2};
                c_1 = 5'b01111 <<< t_3;
                c_r =  ~ c_1[3:0];
                // counter = fi(0,0,counter.WordLength,0,fm);
                // state_reg(1) = 0;
                if (rnd < 16'd60) begin
                  some_length_next = 11'b00000111100;
                end
                else if (rnd > 16'd1514) begin
                  // some_length = fi(LENGTH_MAX_LIMIT, 0, some_length.WordLength, 0, fm);
                  a_0 = rnd[10:0];
                  some_length_next = a_0 >> 8'd1;
                end
                else begin
                  some_length_next = rnd[10:0];
                end
                state_reg_next = 2'b01;
                counter_next = 11'b00000000000;
              end
            end
            else begin
              state_reg_next = 2'b10;
            end
          end
      endcase
    end
    // ---------------- Обновление skid-buffer --------
    if (accept && push) begin
      // В этот такт primary отдаётся получателю, сразу кладём новое слово.
      // (skid быть занятым не может: push требует in_ready=1.)
      p_data_next = push_data;
      p_keep_next = c_r;
      p_last_next = push_last;
      p_valid_temp = 1'b1;
      s_valid_temp = 1'b0;
    end
    else if (accept && ( ! push)) begin
      // primary отдан, нового push нет. Если в skid есть слово — поднимаем его.
      if (s_valid_temp) begin
        p_data_next = s_data;
        p_last_next = s_last;
        p_keep_next = s_keep;
        p_valid_temp = 1'b1;
        s_valid_temp = 1'b0;
      end
      else begin
        p_valid_temp = 1'b0;
      end
    end
    else if (( ! accept) && push) begin
      // Получатель не принимает, а мы уже подтвердили rd_en.
      // Если primary занят — прячем новое слово в skid; иначе — в primary.
      if (p_valid_temp) begin
        s_data_next = push_data;
        s_last_next = push_last;
        s_keep_next = c_r;
        s_valid_temp = 1'b1;
      end
      else begin
        p_data_next = push_data;
        p_last_next = push_last;
        p_keep_next = c_r;
        p_valid_temp = 1'b1;
      end
    end
    // (~accept && ~push) — держим всё как есть.
    m_axis_tdata_1 = p_data;
    m_axis_tvalid_1 = p_valid;
    m_axis_tlast_1 = p_last;
    m_axis_tkeep_1 = p_keep;
    some_length_out_1 = some_length;
    p_valid_next = p_valid_temp;
    s_valid_next = s_valid_temp;
  end



  assign Multiport_Switch_out1 = (corrupt_data_out == 1'b0 ? m_axis_tdata_1 :
              32'b11011110101011011011111011101111);



  assign m_axis_tdata1 = Multiport_Switch_out1;

  assign m_axis_tdata = m_axis_tdata_1;

  assign m_axis_tvalid = m_axis_tvalid_1;

  assign m_axis_tlast = m_axis_tlast_1;

  assign m_axis_tkeep = m_axis_tkeep_1;

  assign some_length_out = some_length_out_1;

endmodule  // AXIS_rnd_master_32bit

